"use client";

import JSZip from "jszip";

type Slide = {
  filename: string;
  svg: string;
};

export default function DownloadAllSvgsButton({
  slides,
  businessName,
}: {
  slides: Slide[];
  businessName?: string;
}) {
  const downloadAll = async () => {
    if (!slides || slides.length === 0) {
      alert("No SVG slides found.");
      return;
    }

    const zip = new JSZip();

    const safeBusinessName =
      businessName
        ?.toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "pitch-deck";

    const folder = zip.folder(`${safeBusinessName}-svg-deck`);

    slides.forEach((slide) => {
      folder?.file(slide.filename, slide.svg);
    });

    const readme = `
Sitora DeckStudio SVG Export

Business:
${businessName || "Unnamed Business"}

Instructions:
1. Unzip this folder.
2. Open Figma.
3. Drag the SVG files into Figma.
4. Refine copy, images, spacing and layout.
5. Export the final reviewed deck as PDF for the client.

Generated by Sitora DeckStudio.
`;

    folder?.file("README.txt", readme.trim());

    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${safeBusinessName}-svg-deck.zip`;

    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={downloadAll}
      className="rounded-full bg-gradient-to-r from-[#c9a44c] to-[#f5d77a] px-6 py-3 text-sm font-semibold text-black transition hover:scale-[1.02]"
    >
      Download All SVGs as ZIP
    </button>
  );
}