export const deckQuestions = [
  {
    id: "founder",
    title: "Founder Details",
    subtitle: "Let’s start with the basics so we can personalise your pitch deck.",
    fields: [
      { name: "business_name", label: "Business name", type: "text", required: true },
      { name: "founder_name", label: "Founder name", type: "text", required: true },
      { name: "email", label: "Email address", type: "email", required: true },
      { name: "phone", label: "Phone number", type: "text" },
      { name: "website", label: "Website", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "industry", label: "Industry / sector", type: "text", required: true },
    ],
  },
  {
    id: "summary",
    title: "Business Summary",
    subtitle: "Explain the business clearly. This becomes the foundation of the pitch.",
    fields: [
      { name: "one_line_pitch", label: "Your one-line pitch", type: "textarea", required: true },
      { name: "business_summary", label: "What does your business do?", type: "textarea", required: true },
      {
        name: "stage",
        label: "What stage is the business at?",
        type: "select",
        options: [
          "Idea stage",
          "Prototype",
          "Pre-revenue",
          "Revenue-generating",
          "Scaling",
          "Fundraising",
          "Established business launching new product",
        ],
      },
    ],
  },
  {
    id: "problem",
    title: "The Problem",
    subtitle: "A good pitch starts with a problem people immediately understand.",
    fields: [
      { name: "problem", label: "What problem are you solving?", type: "textarea", required: true },
      { name: "target_customer", label: "Who experiences this problem?", type: "textarea" },
      { name: "current_solution", label: "What are people using or doing instead?", type: "textarea" },
      { name: "problem_impact", label: "Why does this problem matter?", type: "textarea" },
    ],
  },
  {
    id: "solution",
    title: "The Solution",
    subtitle: "Show how your business solves the problem in a better way.",
    fields: [
      { name: "solution", label: "What is your solution?", type: "textarea", required: true },
      { name: "how_it_works", label: "How does it work?", type: "textarea" },
      { name: "key_benefit", label: "What is the main customer benefit?", type: "textarea" },
      { name: "proof", label: "Do you have any proof, evidence or validation?", type: "textarea" },
    ],
  },
  {
    id: "market",
    title: "Market Opportunity",
    subtitle: "Show the scale, timing and commercial opportunity.",
    fields: [
      { name: "market_size", label: "How big is the market?", type: "textarea" },
      { name: "market_trends", label: "What trends make this the right time?", type: "textarea" },
      { name: "target_region", label: "Which country or region are you starting in?", type: "text" },
      { name: "market_position", label: "Where do you want to position the brand in the market?", type: "textarea" },
    ],
  },
  {
    id: "product",
    title: "Product / Service",
    subtitle: "Explain what the customer gets and how the journey works.",
    fields: [
      { name: "product_features", label: "What are the main features or services?", type: "textarea" },
      { name: "customer_journey", label: "Describe the customer journey", type: "textarea" },
      { name: "customer_journey_step_1", label: "Journey step 1", type: "text" },
      { name: "customer_journey_step_2", label: "Journey step 2", type: "text" },
      { name: "customer_journey_step_3", label: "Journey step 3", type: "text" },
      { name: "customer_journey_step_4", label: "Journey step 4", type: "text" },
      { name: "customer_journey_step_5", label: "Journey step 5", type: "text" },
    ],
  },
  {
    id: "businessModel",
    title: "Business Model",
    subtitle: "Break down exactly how the business makes money.",
    fields: [
      { name: "business_model", label: "How do you make money?", type: "textarea", required: true },
      { name: "pricing", label: "What is your pricing or pricing logic?", type: "textarea" },
      { name: "revenue_streams", label: "List your revenue streams", type: "textarea" },
    ],
  },
  {
    id: "traction",
    title: "Traction / Proof",
    subtitle: "Show evidence that the business is moving.",
    fields: [
      { name: "traction", label: "What traction do you have so far?", type: "textarea" },
      { name: "users_customers", label: "Do you have users, customers or revenue?", type: "textarea" },
      { name: "partnerships", label: "Any partnerships or pipeline?", type: "textarea" },
      { name: "testimonials", label: "Any testimonials or social proof?", type: "textarea" },
      { name: "metric_1_label", label: "Metric 1 label, e.g. Completed projects", type: "text" },
      { name: "metric_1_value", label: "Metric 1 value, e.g. 25+", type: "text" },
      { name: "metric_2_label", label: "Metric 2 label", type: "text" },
      { name: "metric_2_value", label: "Metric 2 value", type: "text" },
      { name: "metric_3_label", label: "Metric 3 label", type: "text" },
      { name: "metric_3_value", label: "Metric 3 value", type: "text" },
    ],
  },
  {
    id: "competition",
    title: "Competition / Advantage",
    subtitle: "Show why the business can win.",
    fields: [
      { name: "competitors", label: "Who are your competitors?", type: "textarea" },
      { name: "competitor_1", label: "Competitor 1", type: "text" },
      { name: "competitor_2", label: "Competitor 2", type: "text" },
      { name: "competitor_3", label: "Competitor 3", type: "text" },
      { name: "competitive_advantage", label: "How are you different?", type: "textarea" },
      { name: "unfair_advantage", label: "What is your unfair advantage?", type: "textarea" },
    ],
  },
  {
  id: "team",
  title: "Team",
  subtitle: "Investors want to know who is building the business and why they are credible.",
  fields: [
    { name: "team_member_1_name", label: "Team member 1 name", type: "text" },
    { name: "team_member_1_role", label: "Team member 1 role", type: "text" },
    { name: "team_member_1_bio", label: "Team member 1 short bio", type: "textarea" },

    { name: "team_member_2_name", label: "Team member 2 name", type: "text" },
    { name: "team_member_2_role", label: "Team member 2 role", type: "text" },
    { name: "team_member_2_bio", label: "Team member 2 short bio", type: "textarea" },

    { name: "team_member_3_name", label: "Team member 3 name", type: "text" },
    { name: "team_member_3_role", label: "Team member 3 role", type: "text" },
    { name: "team_member_3_bio", label: "Team member 3 short bio", type: "textarea" },

    { name: "team_summary", label: "Why is this team credible?", type: "textarea" },
  ],
},
  {
    id: "roadmap",
    title: "3-Year Roadmap",
    subtitle: "Investors want to see where the business is going.",
    fields: [
      { name: "go_to_market", label: "What is your go-to-market strategy?", type: "textarea" },
      { name: "growth_channels", label: "Which growth channels will you use?", type: "textarea" },
      { name: "year_1_plan", label: "Year 1 plan", type: "textarea" },
      { name: "year_2_plan", label: "Year 2 plan", type: "textarea" },
      { name: "year_3_plan", label: "Year 3 plan", type: "textarea" },
    ],
  },
  {
    id: "financials",
    title: "Financials / Investment Ask",
    subtitle: "Give a simple but serious financial view.",
    fields: [
      { name: "current_revenue", label: "Current revenue", type: "text" },
      { name: "year_1_revenue", label: "Projected revenue year 1", type: "text" },
      { name: "year_2_revenue", label: "Projected revenue year 2", type: "text" },
      { name: "year_3_revenue", label: "Projected revenue year 3", type: "text" },
      { name: "funding_needed", label: "How much funding do you need?", type: "text" },
      { name: "use_of_funds", label: "How will the funding be used?", type: "textarea" },
      { name: "use_funds_marketing", label: "Use of funds: marketing / SEO percentage", type: "text" },
      { name: "use_funds_operations", label: "Use of funds: operations percentage", type: "text" },
      { name: "use_funds_product", label: "Use of funds: product / technology percentage", type: "text" },
      { name: "use_funds_team", label: "Use of funds: team percentage", type: "text" },
      { name: "use_funds_other", label: "Use of funds: other percentage", type: "text" },
      { name: "investment_ask", label: "What do you want from investors?", type: "textarea" },
    ],
  },
  {
    id: "visuals",
    title: "Photos / Visual Assets",
    subtitle: "Add image links for Figma placeholders, project proof and final deck polish.",
    fields: [
      { name: "hero_image_url", label: "Hero image URL", type: "text" },
      { name: "project_image_1", label: "Project image 1 URL", type: "text" },
      { name: "project_image_2", label: "Project image 2 URL", type: "text" },
      { name: "project_image_3", label: "Project image 3 URL", type: "text" },
    ],
  },
] as const;