import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, CheckCircle2, ClipboardCheck, FileText, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";

const metrics = [
  { label: "Revenue", value: "SAR 5.24m", delta: "+8.2%", note: "Month to date" },
  { label: "Collections", value: "SAR 4.66m", delta: "+6.9%", note: "88.9% of revenue" },
  { label: "Chair utilisation", value: "78.4%", delta: "+2.6 pts", note: "Group average" },
  { label: "Claims at risk", value: "SAR 143k", delta: "-SAR 18k", note: "Open exposure" },
  { label: "Treatment opportunity", value: "SAR 683.7k", delta: "+SAR 61k", note: "Recoverable pipeline" },
  { label: "Records to review", value: "27", delta: "-6", note: "17 >48 hours" },
];

const boardNarrative = [
  "Group revenue remains above the prior month, but the variance between best and weakest branches is widening.",
  "Jeddah Tahlia is the main downside risk due to lower chair utilisation, concentrated claims exceptions and a larger accepted-but-unbooked queue.",
  "Riyadh North remains the operating benchmark and provides a transferable workflow for treatment conversion and chair management.",
  "Current interventions have an illustrative modeled monthly upside of SAR 126k if execution assumptions hold.",
];

export function BoardPackPreview() {
  return <div className="min-h-screen bg-[#f3efe7] text-[#13211d]">
    <header className="border-b border-black/10 bg-[#f7f3ec]/95"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control/index" className="rounded-xl border border-black/10 p-2.5 text-black/45"><ArrowLeft size={17}/></Link><div><div className="text-[9px] uppercase tracking-[0.17em] text-[#247e73]">Board pack preview</div><div className="mt-1 text-[17px] font-semibold">Noura Dental Group · August 2026</div></div></div><span className="rounded-full border border-black/10 bg-white/50 px-3 py-1.5 text-[9px] uppercase tracking-[0.13em] text-black/40">Synthetic demo</span></div></header>

    <main className="mx-auto max-w-[1280px] px-4 py-8 md:px-7 md:py-11">
      <section className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#247e73]/15 bg-[#247e73]/5 px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.15em] text-[#247e73]"><FileText size={11}/> Executive operating pack</div><h1 className="mt-4 text-[34px] font-semibold tracking-[-0.045em] md:text-[48px]">One board-ready view of performance, risk and intervention.</h1><p className="mt-4 max-w-3xl text-[12px] leading-6 text-black/48">This preview shows how Sitora could turn live operating intelligence into a concise monthly board pack. In production, every number would carry source lineage, scope and refresh metadata.</p></div><div className="rounded-3xl border border-black/10 bg-white/65 p-5 shadow-[0_20px_60px_rgba(0,0,0,0.06)]"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#247e73]">Board headline</div><div className="mt-3 text-[19px] font-semibold leading-7">Performance is positive at group level, but value remains trapped in branch-level execution.</div><p className="mt-3 text-[11px] leading-5 text-black/48">The board discussion should focus on closing the Jeddah operating gap, accelerating accepted-treatment recovery and reducing claims exposure before month end.</p></div></section>

      <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metrics.map((m)=><div key={m.label} className="rounded-2xl border border-black/10 bg-white/65 p-4"><div className="text-[9px] uppercase tracking-[0.11em] text-black/35">{m.label}</div><div className="mt-2 text-[22px] font-semibold tracking-[-0.03em]">{m.value}</div><div className="mt-1 text-[9px] font-medium text-[#247e73]">{m.delta}</div><div className="mt-2 text-[9px] text-black/35">{m.note}</div></div>)}</section>

      <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]"><div className="rounded-3xl border border-black/10 bg-white/65 p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><Sparkles size={15} className="text-[#247e73]"/> Executive narrative</div><div className="mt-4 space-y-3">{boardNarrative.map((item,index)=><div key={item} className="flex gap-3 rounded-2xl border border-black/[0.07] bg-[#faf8f3] p-4"><div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#247e73]/8 text-[10px] font-semibold text-[#247e73]">{index+1}</div><p className="text-[11px] leading-5 text-black/55">{item}</p></div>)}</div></div>
      <div className="rounded-3xl border border-black/10 bg-[#0f2923] p-5 text-white"><div className="flex items-center gap-2 text-[13px] font-semibold"><TrendingUp size={15} className="text-[#79cfc5]"/> Intervention scoreboard</div><div className="mt-4 space-y-3">{[["Jeddah utilisation recovery","COO + Branch Manager","In progress","SAR 54k modeled upside"],["Grouped claims exception workflow","Insurance Lead","In progress","SAR 41.6k exposure"],["Accepted treatment recovery","Commercial Lead","Active","38 priority plans"],["Record completion sprint","Clinical Director","Active","17 records >48h"]].map(([a,b,c,d])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div className="flex items-start justify-between gap-4"><div><div className="text-[11px] font-medium text-white/85">{a}</div><div className="mt-1 text-[9px] text-white/35">{b}</div></div><span className="rounded-full border border-[#79cfc5]/20 bg-[#79cfc5]/8 px-2 py-1 text-[9px] text-[#9fddd5]">{c}</span></div><div className="mt-3 text-[10px] text-[#e2c383]">{d}</div></div>)}</div></div></section>

      <section className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-3xl border border-black/10 bg-white/65 p-5"><div className="flex items-center gap-2 text-[12px] font-semibold"><BarChart3 size={14} className="text-[#247e73]"/> Operating benchmark</div><div className="mt-3 text-[24px] font-semibold">Riyadh North</div><p className="mt-2 text-[10px] leading-5 text-black/45">87% utilisation, 96% governance completeness and the strongest treatment-conversion trend.</p></div><div className="rounded-3xl border border-black/10 bg-white/65 p-5"><div className="flex items-center gap-2 text-[12px] font-semibold"><ClipboardCheck size={14} className="text-[#247e73]"/> Board decisions needed</div><div className="mt-3 text-[24px] font-semibold">3</div><p className="mt-2 text-[10px] leading-5 text-black/45">Jeddah recovery plan, claims workflow ownership and pilot expansion scope.</p></div><div className="rounded-3xl border border-black/10 bg-white/65 p-5"><div className="flex items-center gap-2 text-[12px] font-semibold"><ShieldCheck size={14} className="text-[#247e73]"/> Data confidence</div><div className="mt-3 flex items-center gap-2 text-[24px] font-semibold">High <CheckCircle2 size={18} className="text-[#247e73]"/></div><p className="mt-2 text-[10px] leading-5 text-black/45">Prototype metrics reconcile to synthetic branch totals; production requires source-level validation.</p></div></section>

      <div className="mt-7 flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-black/10 bg-white/55 p-5"><div><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#247e73]">Next review</div><div className="mt-1 text-[14px] font-semibold">Weekly Operating Review · Monday 09:00</div></div><div className="flex gap-2"><Link href="/tools/dental-control/management" className="rounded-xl border border-black/10 px-4 py-2.5 text-[10px] font-medium">Open management review</Link><Link href="/tools/dental-control/command" className="inline-flex items-center gap-2 rounded-xl bg-[#247e73] px-4 py-2.5 text-[10px] font-semibold text-white">Open command centre <ArrowRight size={11}/></Link></div></div>
    </main>
  </div>;
}
