"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, BadgeCheck, CircleDollarSign, Clock3, FileWarning, Gauge, ShieldCheck, Sparkles, TrendingDown, Users, WalletCards } from "lucide-react";
import { clinicianProfiles } from "@/lib/dental-control/deep-data";
import { sar } from "@/lib/dental-control/demo-data";

export function ClinicianProfile({ clinicianId }: { clinicianId: string }) {
  const clinician = clinicianProfiles[clinicianId as keyof typeof clinicianProfiles] ?? clinicianProfiles["dr-faisal-al-zahrani"];
  return <div className="min-h-screen bg-[#071310] text-white">
    <header className="border-b border-white/[0.06] bg-[#081713]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control/branch/jeddah-tahlia" className="rounded-xl border border-white/[0.08] p-2.5 text-white/50"><ArrowLeft size={17}/></Link><div><div className="text-[10px] uppercase tracking-[0.17em] text-[#73cabf]">Clinician intelligence</div><div className="mt-1 text-[17px] font-semibold">{clinician.name}</div></div></div><span className="hidden rounded-full border border-[#c49a53]/20 bg-[#c49a53]/8 px-3 py-1.5 text-[9px] uppercase tracking-[0.14em] text-[#e4c489] sm:inline-flex">Balanced performance view</span></div></header>
    <main className="mx-auto max-w-[1440px] px-4 py-6 md:px-7 md:py-8">
      <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#2aa89a] to-[#176359] text-[16px] font-bold">{clinician.avatar}</div><div><div className="text-[25px] font-semibold tracking-[-0.03em]">{clinician.name}</div><div className="mt-1 text-[11px] text-white/35">{clinician.specialty} · {clinician.branch}</div><div className="mt-3 inline-flex items-center gap-2 rounded-full border border-amber-400/15 bg-amber-400/[0.05] px-2.5 py-1 text-[9px] text-amber-200"><TrendingDown size={11}/>{Math.abs(clinician.trend)}% revenue trend</div></div></div><p className="mt-6 text-[12px] leading-6 text-white/42">{clinician.sitoraSummary}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Revenue" value={sar(clinician.revenue)} sub={`${sar(clinician.contribution)} contribution`}/><Metric icon={Gauge} label="Utilisation" value={`${clinician.utilisation}%`} sub="11 pts below branch" warn/><Metric icon={BadgeCheck} label="Acceptance" value={`${clinician.treatmentAcceptance}%`} sub="Healthy demand signal"/><Metric icon={ShieldCheck} label="Records" value={`${clinician.recordCompleteness}%`} sub="3 records in review" warn/></div></div>
        <div className="rounded-3xl border border-[#2aa89a]/16 bg-gradient-to-br from-[#0d2822] to-[#0a1a16] p-5"><div className="flex items-center gap-2 text-[12px] font-semibold"><Sparkles size={15} className="text-[#75cbbf]"/> Sitora interpretation</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><Insight title="Strengths" items={clinician.strengths} tone="good"/><Insight title="Watchouts" items={clinician.watchouts} tone="warn"/></div><div className="mt-4 rounded-xl border border-[#c49a53]/15 bg-[#c49a53]/[0.04] p-3 text-[10px] leading-5 text-white/45"><span className="font-semibold text-[#e3c183]">Management view:</span> do not treat this as a clinician revenue problem. The leading signal is unfilled capacity combined with workflow friction.</div></div>
      </section>

      <section className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
        <Panel title="Four-week pattern" subtitle="Utilisation and revenue moving together"><div className="space-y-3">{clinician.weekly.map(week=><div key={week.week} className="rounded-xl border border-white/[0.05] bg-white/[0.02] p-3"><div className="flex items-center justify-between text-[10px]"><span className="text-white/38">{week.week}</span><span className="text-white/70">{sar(week.revenue)}</span></div><div className="mt-2 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/[0.05]"><div className="h-full rounded-full bg-[#2aa89a]" style={{width:`${week.utilisation}%`}}/></div><span className="w-10 text-right text-[9px] text-white/40">{week.utilisation}%</span></div></div>)}</div></Panel>
        <Panel title="Recent case signals" subtitle="The clinician profile is tied back to actual operational workflows"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="text-[9px] uppercase tracking-[0.12em] text-white/22"><tr><th className="pb-3">Patient</th><th className="pb-3">Procedure</th><th className="pb-3">Value</th><th className="pb-3">Status</th><th className="pb-3">Time</th></tr></thead><tbody>{clinician.recentCases.map((c,index)=><tr key={`${c.patient}-${index}`} className="border-t border-white/[0.05] text-[10px]"><td className="py-3.5 text-white/60">{c.patient}</td><td className="py-3.5 text-white/55">{c.procedure}</td><td className="py-3.5 text-white/65">{sar(c.value)}</td><td className="py-3.5"><span className={`rounded-full border px-2 py-1 text-[8px] ${c.status.includes('Claim')||c.status.includes('Record')||c.status.includes('unbooked')?'border-amber-400/15 bg-amber-400/[0.05] text-amber-200':'border-emerald-400/15 bg-emerald-400/[0.05] text-emerald-200'}`}>{c.status}</span></td><td className="py-3.5 text-white/30">{c.time}</td></tr>)}</tbody></table></div><Link href="/tools/dental-control/patient/J-11307" className="mt-4 inline-flex items-center gap-1 text-[10px] font-medium text-[#75cbbf]">Open accepted treatment story <ArrowRight size={10}/></Link></Panel>
      </section>
    </main>
  </div>;
}

function Metric({icon:Icon,label,value,sub,warn}:{icon:typeof Users;label:string;value:string;sub:string;warn?:boolean}){return <div className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-3.5"><Icon size={14} className={warn?'text-amber-200':'text-[#76cbbf]'}/><div className="mt-3 text-[9px] uppercase tracking-[0.11em] text-white/22">{label}</div><div className={`mt-1 text-[17px] font-semibold ${warn?'text-amber-100':''}`}>{value}</div><div className="mt-1 text-[8px] text-white/24">{sub}</div></div>}
function Insight({title,items,tone}:{title:string;items:string[];tone:'good'|'warn'}){return <div className={`rounded-2xl border p-4 ${tone==='good'?'border-emerald-400/12 bg-emerald-400/[0.03]':'border-amber-400/12 bg-amber-400/[0.03]'}`}><div className={`text-[10px] font-semibold uppercase tracking-[0.13em] ${tone==='good'?'text-emerald-200':'text-amber-200'}`}>{title}</div><div className="mt-3 space-y-2">{items.map(i=><div key={i} className="text-[10px] leading-5 text-white/40">• {i}</div>)}</div></div>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="rounded-3xl border border-white/[0.07] bg-white/[0.025]"><div className="border-b border-white/[0.06] px-5 py-4"><div className="text-[13px] font-semibold">{title}</div><div className="mt-1 text-[10px] text-white/27">{subtitle}</div></div><div className="p-5">{children}</div></section>}
