"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Calculator, CircleDollarSign, Gauge, Layers3, Sparkles, TrendingUp } from "lucide-react";
import { branchPnL, calculateRoi, pricingTiers, roiModel, valueCase } from "@/lib/dental-control/commercial-data";

function sar(value: number) {
  return `SAR ${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value)}`;
}

export function CommercialCase() {
  const [monthlyFee, setMonthlyFee] = useState(18000);
  const roi = useMemo(() => calculateRoi(monthlyFee), [monthlyFee]);

  return <div className="min-h-screen bg-[#071310] text-white">
    <header className="border-b border-white/[0.06] bg-[#081713]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1380px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control/index" className="rounded-xl border border-white/[0.08] p-2.5 text-white/50"><ArrowLeft size={17}/></Link><div><div className="text-[10px] uppercase tracking-[0.17em] text-[#73cabf]">Commercial model</div><div className="mt-1 text-[17px] font-semibold">Sitora Value & ROI Case</div></div></div><Link href="/tools/dental-control/pilot" className="rounded-xl bg-[#2aa89a] px-4 py-2.5 text-[10px] font-semibold text-[#04110f]">Build pilot case</Link></div></header>

    <main className="mx-auto max-w-[1380px] px-4 py-8 md:px-7 md:py-10">
      <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#2aa89a]/18 bg-[#2aa89a]/[0.05] px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#78cfc4]"><Sparkles size={12}/> From product value to investment case</div><h1 className="mt-4 max-w-4xl text-[34px] font-semibold tracking-[-0.045em] md:text-[48px]">Show why a dental group would pay for Sitora.</h1><p className="mt-4 max-w-3xl text-[12px] leading-6 text-white/40">This model turns the prototype’s operating signals into a commercial case. All values are synthetic and assumptions are explicit so a buyer can challenge them rather than being shown a black-box ROI number.</p></div>
        <div className="rounded-3xl border border-[#2aa89a]/18 bg-gradient-to-br from-[#0d2822] to-[#0a1a16] p-5"><div className="flex items-center gap-2 text-[11px] font-semibold"><Calculator size={15} className="text-[#79cfc5]"/> Assumption-controlled ROI</div><div className="mt-4"><label className="text-[9px] uppercase tracking-[0.13em] text-white/26">Illustrative monthly SaaS fee</label><div className="mt-2 flex items-center gap-3"><input type="range" min="8000" max="50000" step="1000" value={monthlyFee} onChange={e=>setMonthlyFee(Number(e.target.value))} className="w-full"/><div className="min-w-[100px] text-right text-[14px] font-semibold">{sar(monthlyFee)}</div></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/25">Gross modeled benefit</div><div className="mt-2 text-[21px] font-semibold text-emerald-200">{sar(roi.grossMonthlyBenefit)}</div><div className="mt-1 text-[9px] text-white/28">per month</div></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/25">Benefit / fee</div><div className="mt-2 text-[21px] font-semibold text-[#7bcfc5]">{roi.roiMultiple.toFixed(1)}×</div><div className="mt-1 text-[9px] text-white/28">illustrative multiple</div></div></div><div className="mt-3 rounded-2xl border border-[#c49a53]/14 bg-[#c49a53]/[0.035] p-3 text-[9px] leading-5 text-white/38">Modeled payback is approximately <span className="font-semibold text-[#e3c183]">{roi.paybackDays} days</span>. This is a scenario, not a guaranteed financial outcome.</div></div>
      </section>

      <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {[
          ["Treatment recovery", roi.treatment, `${Math.round(roiModel.assumedTreatmentRecoveryRate*100)}% of current opportunity`],
          ["Claims recovery", roi.claims, `${Math.round(roiModel.assumedClaimsRecoveryRate*100)}% of exposed claims`],
          ["Capacity recovery", roi.capacity, `${Math.round(roiModel.assumedCapacityRecoveryRate*100)}% of unused chair capacity`],
          ["Admin efficiency", roi.admin, `${Math.round(roiModel.assumedAdminReductionRate*100)}% of selected admin effort`],
        ].map(([label,value,sub])=><div key={String(label)} className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="text-[9px] uppercase tracking-[0.12em] text-white/24">{label}</div><div className="mt-2 text-[22px] font-semibold">{sar(Number(value))}</div><div className="mt-1 text-[9px] text-white/28">{sub}</div></div>)}
      </section>

      <section className="mt-6 grid gap-5 2xl:grid-cols-[1.15fr_0.85fr]">
        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><CircleDollarSign size={15} className="text-[#73cabf]"/> Branch contribution view</div><p className="mt-2 text-[10px] leading-5 text-white/30">A simplified P&L layer shows why revenue alone is not enough. Leadership can compare contribution after major attributable cost categories.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="text-[9px] uppercase tracking-[0.12em] text-white/22"><tr><th className="pb-3">Branch</th><th className="pb-3">Revenue</th><th className="pb-3">Clinician</th><th className="pb-3">Lab</th><th className="pb-3">Materials</th><th className="pb-3">Support</th><th className="pb-3">Occupancy</th><th className="pb-3">Contribution</th></tr></thead><tbody>{branchPnL.map(row=><tr key={row.branch} className="border-t border-white/[0.05] text-[10px]"><td className="py-3.5 font-medium text-white/74">{row.branch}</td><td className="py-3.5 text-white/55">{sar(row.revenue)}</td><td className="py-3.5 text-white/38">{sar(row.clinicianCost)}</td><td className="py-3.5 text-white/38">{sar(row.labCost)}</td><td className="py-3.5 text-white/38">{sar(row.materials)}</td><td className="py-3.5 text-white/38">{sar(row.supportCost)}</td><td className="py-3.5 text-white/38">{sar(row.occupancy)}</td><td className="py-3.5 font-semibold text-[#79cfc5]">{sar(row.contribution)}</td></tr>)}</tbody></table></div></div>

        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><TrendingUp size={15} className="text-[#73cabf]"/> Before vs after operating model</div><div className="mt-4 space-y-2.5">{valueCase.map(item=><div key={item.area} className="rounded-2xl border border-white/[0.055] bg-white/[0.02] p-3.5"><div className="text-[10px] font-semibold text-white/72">{item.area}</div><div className="mt-2 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-white/[0.025] p-2.5"><div className="text-[8px] uppercase tracking-[0.12em] text-white/20">Before</div><div className="mt-1 text-[9px] leading-4 text-white/36">{item.before}</div></div><div className="rounded-xl bg-[#2aa89a]/[0.045] p-2.5"><div className="text-[8px] uppercase tracking-[0.12em] text-[#72cabf]">With Sitora</div><div className="mt-1 text-[9px] leading-4 text-white/48">{item.after}</div></div></div><div className="mt-2 text-[9px] text-[#e2c285]">Impact: {item.impact}</div></div>)}</div></div>
      </section>

      <section className="mt-6"><div className="mb-3 flex items-center gap-2 text-[13px] font-semibold"><Layers3 size={15} className="text-[#73cabf]"/> Illustrative SaaS packaging</div><div className="grid gap-4 lg:grid-cols-3">{pricingTiers.map(tier=><div key={tier.name} className={`rounded-3xl border p-5 ${tier.name==="Group"?"border-[#2aa89a]/25 bg-[#2aa89a]/[0.045]":"border-white/[0.07] bg-white/[0.025]"}`}><div className="flex items-center justify-between"><div className="text-[15px] font-semibold">{tier.name}</div>{tier.name==="Group"?<span className="rounded-full border border-[#2aa89a]/20 px-2 py-1 text-[8px] uppercase tracking-[0.12em] text-[#7bcfc5]">Prototype fit</span>:null}</div><div className="mt-4 text-[26px] font-semibold">{tier.monthly?`${sar(tier.monthly)}/mo`:"Custom"}</div><div className="mt-1 text-[9px] text-white/28">{tier.note}</div><div className="mt-4 grid grid-cols-2 gap-2 text-[9px]"><div className="rounded-xl bg-white/[0.025] p-2.5"><div className="text-white/20">Branches</div><div className="mt-1 text-white/55">{tier.branches}</div></div><div className="rounded-xl bg-white/[0.025] p-2.5"><div className="text-white/20">Users</div><div className="mt-1 text-white/55">{tier.users}</div></div></div><div className="mt-4 space-y-2">{tier.modules.map(module=><div key={module} className="flex items-center gap-2 text-[9px] text-white/42"><Gauge size={10} className="text-[#72cabf]"/>{module}</div>)}</div></div>)}</div></section>
    </main>
  </div>;
}
