"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeDollarSign, Building2, Layers3, LineChart, Rocket, ShieldCheck, Sparkles, Target } from "lucide-react";
import { expansionModules, investorEconomics, marketFrames, moatLayers, salesMotion } from "@/lib/dental-control/investor-data";

function sar(value: number) {
  return `SAR ${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value)}`;
}

export function InvestorEconomics() {
  const [customers, setCustomers] = useState(50);
  const [arrPerCustomer, setArrPerCustomer] = useState(investorEconomics.pricing.blendedArrPerCustomer);
  const modeled = useMemo(() => {
    const arr = customers * arrPerCustomer;
    const grossProfit = arr * investorEconomics.pricing.grossMarginTarget;
    return { arr, grossProfit };
  }, [customers, arrPerCustomer]);

  return <div className="min-h-screen bg-[#071310] text-white">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_82%_4%,rgba(42,168,154,0.12),transparent_30%),radial-gradient(circle_at_15%_92%,rgba(196,154,83,0.08),transparent_23%)]" />
    <header className="relative border-b border-white/[0.06] bg-[#081713]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1360px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control/index" className="rounded-xl border border-white/[0.08] p-2.5 text-white/50"><ArrowLeft size={17}/></Link><div><div className="text-[10px] uppercase tracking-[0.17em] text-[#73cabf]">Investor layer</div><div className="mt-1 text-[17px] font-semibold">Economics & Scale Model</div></div></div><span className="hidden rounded-full border border-[#c49a53]/20 bg-[#c49a53]/8 px-3 py-1.5 text-[9px] uppercase tracking-[0.14em] text-[#e3c183] sm:inline-flex"><Sparkles size={11} className="mr-1.5"/> Illustrative model</span></div></header>

    <main className="relative mx-auto max-w-[1360px] px-4 py-8 md:px-7 md:py-10">
      <section className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#2aa89a]/18 bg-[#2aa89a]/[0.05] px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#78cfc4]"><Rocket size={12}/> SaaS scale thesis</div><h1 className="mt-4 max-w-4xl text-[34px] font-semibold tracking-[-0.045em] md:text-[48px]">Land with operating intelligence. Expand into the dental group operating system.</h1><p className="mt-4 max-w-3xl text-[12px] leading-6 text-white/42">The investment case is not one dashboard sold once. The thesis is a multi-module intelligence platform that lands through a measurable operational problem, expands across branches and functions, and compounds through connectors, workflow history and evidence-backed AI.</p></div>
        <div className="rounded-3xl border border-[#2aa89a]/16 bg-gradient-to-br from-[#0d2822] to-[#0a1a16] p-5"><div className="text-[10px] uppercase tracking-[0.15em] text-[#78cfc4]">Illustrative blended customer</div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/28">Blended ARR</div><div className="mt-1 text-[21px] font-semibold">{sar(investorEconomics.pricing.blendedArrPerCustomer)}</div></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/28">Target gross margin</div><div className="mt-1 text-[21px] font-semibold">84%</div></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/28">Year 3 NRR thesis</div><div className="mt-1 text-[21px] font-semibold">122%</div></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4"><div className="text-[9px] text-white/28">Mature modules</div><div className="mt-1 text-[21px] font-semibold">7+</div></div></div><div className="mt-3 text-[9px] leading-5 text-white/25">These are planning assumptions for prototype storytelling, not audited forecasts or market claims.</div></div>
      </section>

      <section className="mt-6 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-[13px] font-semibold"><LineChart size={15} className="text-[#73cabf]"/> Interactive ARR model</div><p className="mt-1 text-[10px] text-white/30">Change customer count and blended ARR to show the shape of the model.</p></div><div className="text-right"><div className="text-[10px] text-white/28">Modeled ARR</div><div className="text-[25px] font-semibold text-[#83d2c8]">{sar(modeled.arr)}</div></div></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr_0.8fr]"><div><div className="flex items-center justify-between text-[10px]"><span className="text-white/40">Customer groups</span><span className="font-semibold">{customers}</span></div><input type="range" min={10} max={500} step={10} value={customers} onChange={e=>setCustomers(Number(e.target.value))} className="mt-3 w-full accent-[#2aa89a]"/></div><div><div className="flex items-center justify-between text-[10px]"><span className="text-white/40">ARR / customer</span><span className="font-semibold">{sar(arrPerCustomer)}</span></div><input type="range" min={120000} max={480000} step={15000} value={arrPerCustomer} onChange={e=>setArrPerCustomer(Number(e.target.value))} className="mt-3 w-full accent-[#c49a53]"/></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="text-[9px] text-white/28">Modeled gross profit</div><div className="mt-1 text-[20px] font-semibold">{sar(modeled.grossProfit)}</div><div className="mt-1 text-[9px] text-white/24">At 84% illustrative GM</div></div></div></section>

      <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{investorEconomics.scenarios.map(row=><div key={row.groups} className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center justify-between"><div className="text-[10px] uppercase tracking-[0.14em] text-white/28">{row.groups} groups</div><Building2 size={15} className="text-[#73cabf]"/></div><div className="mt-4 text-[22px] font-semibold">{sar(row.arr)}</div><div className="mt-1 text-[9px] text-white/25">Illustrative ARR</div><div className="mt-4 border-t border-white/[0.05] pt-3 text-[10px] leading-5 text-white/36">{row.note}</div></div>)}</section>

      <section className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><Target size={15} className="text-[#73cabf]"/> Market framing</div><div className="mt-4 space-y-3">{marketFrames.map(item=><div key={item.label} className="rounded-2xl border border-white/[0.055] bg-white/[0.025] p-4"><div className="text-[9px] uppercase tracking-[0.13em] text-[#e3c183]">{item.label}</div><div className="mt-2 text-[12px] font-medium text-white/80">{item.value}</div><p className="mt-2 text-[10px] leading-5 text-white/34">{item.detail}</p></div>)}</div></div>
        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><Layers3 size={15} className="text-[#73cabf]"/> Land-and-expand surface</div><p className="mt-1 text-[10px] text-white/30">Illustrative contract expansion potential as modules are activated.</p><div className="mt-4 space-y-3">{expansionModules.map((item,index)=><div key={item.module}><div className="flex items-center justify-between text-[10px]"><span className="text-white/52">{index+1}. {item.module}</span><span className={item.stage === "Land" ? "text-[#79cfc5]" : "text-[#e3c183]"}>{item.stage}{item.uplift ? ` · +${Math.round(item.uplift*100)}%` : ""}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><div className="h-full rounded-full bg-gradient-to-r from-[#2aa89a] to-[#c49a53]" style={{width:`${35+index*9}%`}}/></div></div>)}</div></div>
      </section>

      <section className="mt-5 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex items-center gap-2 text-[13px] font-semibold"><BadgeDollarSign size={15} className="text-[#73cabf]"/> Enterprise sales motion</div><div className="mt-5 grid gap-3 xl:grid-cols-5">{salesMotion.map(item=><div key={item.stage} className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#2aa89a]/12 text-[10px] font-semibold text-[#79cfc5]">{item.stage}</div><div className="mt-3 text-[11px] font-semibold text-white/80">{item.title}</div><p className="mt-2 text-[10px] leading-5 text-white/34">{item.detail}</p></div>)}</div></section>

      <section className="mt-5 rounded-3xl border border-[#c49a53]/14 bg-[#c49a53]/[0.03] p-5 md:p-6"><div className="flex items-center gap-2 text-[13px] font-semibold"><ShieldCheck size={15} className="text-[#e3c183]"/> Why the moat can deepen</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{moatLayers.map(item=><div key={item.title} className="rounded-2xl border border-white/[0.055] bg-black/10 p-4"><div className="text-[11px] font-medium text-white/80">{item.title}</div><p className="mt-2 text-[10px] leading-5 text-white/34">{item.detail}</p></div>)}</div></section>

      <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><Link href="/tools/dental-control/commercial" className="inline-flex items-center gap-2 text-[10px] text-white/42"><ArrowLeft size={12}/> Customer ROI case</Link><Link href="/tools/dental-control/pilot" className="inline-flex items-center gap-2 rounded-xl bg-[#2aa89a] px-4 py-3 text-[10px] font-semibold text-[#04110f]">Open pilot builder <ArrowRight size={12}/></Link></div>
    </main>
  </div>;
}
