"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, FileWarning, ShieldCheck, Stethoscope, UserRound, WalletCards } from "lucide-react";
import { branches, clinicians, claims, governanceRecords, actions, sar } from "@/lib/dental-control/demo-data";

type RoleKey = "CEO" | "Branch Manager" | "Insurance Team" | "Clinical Director" | "Dentist";

const roles: { key: RoleKey; icon: typeof Building2; scope: string; promise: string }[] = [
  { key: "CEO", icon: BriefcaseBusiness, scope: "All 8 branches", promise: "Group performance, risk, forecast and decisions" },
  { key: "Branch Manager", icon: Building2, scope: "Jeddah Tahlia only", promise: "Local operations, chairs, people and actions" },
  { key: "Insurance Team", icon: WalletCards, scope: "Claims work queue", promise: "Exceptions, value at risk and deadlines" },
  { key: "Clinical Director", icon: ShieldCheck, scope: "Clinical governance", promise: "Documentation, review queues and quality signals" },
  { key: "Dentist", icon: Stethoscope, scope: "Own workload only", promise: "My patients, records, actions and schedule" },
];

function Metric({ label, value, sub }: { label: string; value: string; sub: string }) {
  return <div className="rounded-2xl border border-white/[0.07] bg-white/[0.03] p-4"><div className="text-[9px] uppercase tracking-[0.14em] text-white/25">{label}</div><div className="mt-2 text-[22px] font-semibold tracking-[-0.03em] text-white">{value}</div><div className="mt-1 text-[10px] text-white/30">{sub}</div></div>;
}

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#071310] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_80%_0%,rgba(42,168,154,.11),transparent_32%),radial-gradient(circle_at_15%_100%,rgba(196,154,83,.07),transparent_26%)]"/><main className="relative mx-auto max-w-[1450px] px-4 py-6 md:px-7 md:py-9">{children}</main></div>;
}

function CeoView() {
  const attention = branches.filter(b => b.status === "attention");
  return <div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Revenue" value={sar(branches.reduce((s,b)=>s+b.revenue,0))} sub="Group month to date"/><Metric label="Claims risk" value={sar(branches.reduce((s,b)=>s+b.claimsRisk,0))} sub="Across all branches"/><Metric label="Treatment opportunity" value={sar(branches.reduce((s,b)=>s+b.treatmentOpportunity,0))} sub="Recoverable pipeline"/><Metric label="Branches at risk" value={`${attention.length}`} sub="Need executive attention"/><Metric label="Open actions" value={`${actions.filter(a=>a.status!=="Resolved").length}`} sub="Tracked interventions"/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="text-[13px] font-semibold">CEO priority map</div><div className="mt-4 space-y-2">{branches.map(b=><div key={b.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 rounded-2xl border border-white/[0.05] bg-white/[0.02] p-3.5 text-[10px]"><div><div className="font-medium text-white/75">{b.name}</div><div className="mt-1 text-white/26">{b.clinicians} clinicians · {b.chairs} chairs</div></div><div className={b.status==="attention"?"text-amber-200":"text-white/45"}>{b.utilisation}% utilisation</div><div className="text-[#77cbbf]">{sar(b.treatmentOpportunity)}</div></div>)}</div></section><section className="rounded-3xl border border-[#2aa89a]/16 bg-[#0b211c] p-5"><div className="text-[10px] uppercase tracking-[.14em] text-[#79cfc5]">CEO lens</div><div className="mt-3 text-[18px] font-semibold">Only show what changes a group-level decision.</div><p className="mt-3 text-[11px] leading-5 text-white/40">No patient-level detail by default. The CEO sees performance, risk, forecast and accountable actions, with drill-down available only when needed.</p><Link href="/tools/dental-control/command" className="mt-5 inline-flex items-center gap-2 text-[10px] font-medium text-[#79cfc5]">Open Command Centre <ArrowRight size={11}/></Link></section></div></div>;
}

function BranchManagerView() {
  const branch = branches.find(b=>b.id==="jeddah-tahlia")!;
  const localClinicians = clinicians.filter(c=>c.branch==="Jeddah Tahlia");
  const localActions = actions.filter(a=>a.branch==="Jeddah Tahlia");
  return <div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Revenue" value={sar(branch.revenue)} sub="Jeddah Tahlia"/><Metric label="Chair utilisation" value={`${branch.utilisation}%`} sub="Below group benchmark"/><Metric label="Opportunity" value={sar(branch.treatmentOpportunity)} sub="Local recoverable pipeline"/><Metric label="Claims risk" value={sar(branch.claimsRisk)} sub="Local only"/><Metric label="My open actions" value={`${localActions.filter(a=>a.status!=="Resolved").length}`} sub="Assigned to branch workflow"/></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="text-[13px] font-semibold">Team operating view</div><div className="mt-4 space-y-2">{localClinicians.map(c=><div key={c.id} className="rounded-2xl border border-white/[0.05] bg-white/[0.02] p-3.5"><div className="flex items-center justify-between"><div><div className="text-[11px] font-medium text-white/75">{c.name}</div><div className="mt-1 text-[9px] text-white/25">{c.specialty}</div></div><div className="text-right text-[10px]"><div className="text-white/55">{c.utilisation}% utilisation</div><div className="mt-1 text-white/30">{c.recordCompleteness}% records</div></div></div></div>)}</div></section><section className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="text-[13px] font-semibold">Branch actions</div><div className="mt-4 space-y-2">{localActions.map(a=><div key={a.id} className="rounded-2xl border border-white/[0.05] bg-white/[0.02] p-3.5"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-medium text-white/75">{a.title}</div><div className="mt-1 text-[9px] text-white/26">Owner: {a.owner} · Due {a.due}</div></div><span className="rounded-full border border-white/[0.07] px-2 py-1 text-[8px] text-white/35">{a.status}</span></div></div>)}</div></section></div></div>;
}

function InsuranceView() {
  return <div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Claims in queue" value={`${claims.length}`} sub="Synthetic exceptions"/><Metric label="Value exposed" value={sar(claims.reduce((s,c)=>s+c.value,0))} sub="Current queue"/><Metric label="Jeddah cluster" value={`${claims.filter(c=>c.branch.includes("Jeddah")).length}`} sub="Needs grouped review"/><Metric label="Oldest exception" value={`${Math.max(...claims.map(c=>c.ageHours))}h`} sub="Action window"/></div><section className="mt-5 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><FileWarning size={15} className="text-amber-200"/> Insurance work queue</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-[10px]"><thead className="text-[9px] uppercase tracking-[.13em] text-white/22"><tr><th className="pb-3">Claim</th><th className="pb-3">Branch</th><th className="pb-3">Procedure</th><th className="pb-3">Value</th><th className="pb-3">Reason</th><th className="pb-3">Age</th></tr></thead><tbody>{claims.map(c=><tr key={c.id} className="border-t border-white/[0.05]"><td className="py-3.5 text-white/70">{c.id}</td><td className="py-3.5 text-white/45">{c.branch}</td><td className="py-3.5 text-white/50">{c.procedure}</td><td className="py-3.5 text-white/65">{sar(c.value)}</td><td className="py-3.5 text-white/38">{c.reason}</td><td className="py-3.5 text-amber-100/70">{c.ageHours}h</td></tr>)}</tbody></table></div></section></div>;
}

function ClinicalDirectorView() {
  return <div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Records in review" value={`${governanceRecords.length}`} sub="Synthetic queue"/><Metric label="Older than 48h" value={`${governanceRecords.filter(r=>r.ageHours>48).length}`} sub="Priority review"/><Metric label="Lowest completeness" value={`${Math.min(...governanceRecords.map(r=>r.completeness))}%`} sub="Needs attention"/><Metric label="Scope" value="Group-wide" sub="Governance only"/></div><section className="mt-5 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><ShieldCheck size={15} className="text-[#78cfc4]"/> Governance review queue</div><div className="mt-4 grid gap-3 lg:grid-cols-2">{governanceRecords.map(r=><div key={r.id} className="rounded-2xl border border-white/[0.05] bg-white/[0.02] p-4"><div className="flex items-start justify-between"><div><div className="text-[11px] font-medium text-white/75">{r.procedure}</div><div className="mt-1 text-[9px] text-white/25">{r.branch} · {r.clinician}</div></div><div className={r.completeness<85?"text-amber-200":"text-[#79cfc5]"}>{r.completeness}%</div></div><div className="mt-3 text-[9px] text-white/30">{r.missing.join(" · ")}</div></div>)}</div></section></div>;
}

function DentistView() {
  const dentist = clinicians.find(c=>c.name.includes("Reem")) ?? clinicians[0];
  const ownRecords = governanceRecords.filter(r=>r.clinician===dentist.name);
  return <div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="My utilisation" value={`${dentist.utilisation}%`} sub="Current month"/><Metric label="My revenue/hour" value={`SAR ${dentist.revenueHour}`} sub="Context only"/><Metric label="My record completeness" value={`${dentist.recordCompleteness}%`} sub="Documentation"/><Metric label="My claim rejection" value={`${dentist.claimRejection}%`} sub="Own claims"/><Metric label="My return rate" value={`${dentist.returnRate}%`} sub="Patient continuity"/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.75fr]"><section className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-[13px] font-semibold"><UserRound size={15} className="text-[#78cfc4]"/> My work queue</div><div className="mt-4 space-y-2">{ownRecords.length?ownRecords.map(r=><div key={r.id} className="rounded-2xl border border-white/[0.05] bg-white/[0.02] p-4"><div className="text-[11px] font-medium text-white/75">Complete record: {r.procedure}</div><div className="mt-1 text-[9px] text-white/26">{r.patient} · {r.ageHours}h old</div><div className="mt-3 flex items-center gap-2 text-[9px] text-amber-100/70"><ClipboardCheck size={11}/> Missing: {r.missing.join(", ")}</div></div>):<div className="rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.035] p-4 text-[10px] text-emerald-100/70"><CheckCircle2 size={13} className="mb-2"/>No record actions currently assigned.</div>}</div></section><section className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="text-[13px] font-semibold">Privacy boundary</div><p className="mt-3 text-[11px] leading-5 text-white/38">The dentist sees their own workload and performance context, not another clinician&apos;s patient records, detailed revenue or unrelated branch queues.</p></section></div></div>;
}

export function RoleBasedWorkspaces() {
  const [role, setRole] = useState<RoleKey>("CEO");
  const current = useMemo(()=>roles.find(r=>r.key===role)!,[role]);
  return <Shell><header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/tools/dental-control/index" className="inline-flex items-center gap-2 text-[10px] text-white/35"><ArrowLeft size={12}/> Prototype map</Link><div className="mt-4 text-[10px] font-semibold uppercase tracking-[.17em] text-[#78cfc4]">Role-based access prototype</div><h1 className="mt-2 text-[32px] font-semibold tracking-[-.04em] md:text-[43px]">The same platform. Five materially different workspaces.</h1><p className="mt-3 max-w-3xl text-[11px] leading-6 text-white/38">Use the role switcher to show how scope, metrics and actions change with responsibility. This is the front-end prototype of the RBAC and tenant-isolation model.</p></div><div className="rounded-2xl border border-[#c49a53]/16 bg-[#c49a53]/[.035] px-4 py-3"><div className="text-[9px] uppercase tracking-[.13em] text-[#e1c080]">Current scope</div><div className="mt-1 text-[12px] font-medium">{current.scope}</div></div></header><div className="mt-6 grid gap-3 md:grid-cols-5">{roles.map(({key,icon:Icon,scope,promise})=><button key={key} onClick={()=>setRole(key)} className={`rounded-2xl border p-4 text-left transition ${role===key?"border-[#2aa89a]/30 bg-[#2aa89a]/[.07]":"border-white/[.06] bg-white/[.02] hover:bg-white/[.035]"}`}><div className="flex items-center gap-2"><Icon size={14} className={role===key?"text-[#79cfc5]":"text-white/28"}/><div className="text-[11px] font-medium text-white/75">{key}</div></div><div className="mt-3 text-[9px] text-white/24">{scope}</div><div className="mt-1 text-[9px] leading-4 text-white/34">{promise}</div></button>)}</div><div className="mt-6">{role==="CEO"?<CeoView/>:role==="Branch Manager"?<BranchManagerView/>:role==="Insurance Team"?<InsuranceView/>:role==="Clinical Director"?<ClinicalDirectorView/>:<DentistView/>}</div></Shell>;
}