"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Layers3, PlayCircle, Sparkles } from "lucide-react";
import { demoJourney, platformLayers } from "@/lib/dental-control/deep-data";

export function VCDemoJourney() {
  return <div className="min-h-screen bg-[#071310] text-white">
    <header className="border-b border-white/[0.06] bg-[#081713]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1320px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control" className="rounded-xl border border-white/[0.08] p-2.5 text-white/50"><ArrowLeft size={17}/></Link><div><div className="text-[10px] uppercase tracking-[0.17em] text-[#73cabf]">Presenter mode</div><div className="mt-1 text-[17px] font-semibold">Sitora Dental Control · VC Demo</div></div></div><span className="hidden rounded-full border border-[#c49a53]/20 bg-[#c49a53]/8 px-3 py-1.5 text-[9px] uppercase tracking-[0.14em] text-[#e3c183] sm:inline-flex"><Sparkles size={11} className="mr-1.5"/> 5-minute story</span></div></header>
    <main className="mx-auto max-w-[1320px] px-4 py-7 md:px-7 md:py-9">
      <section className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#2aa89a]/18 bg-[#2aa89a]/[0.05] px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#78cfc4]"><PlayCircle size={12}/> Guided executive story</div><h1 className="mt-4 max-w-3xl text-[32px] font-semibold tracking-[-0.04em] md:text-[44px]">Show how one weak signal becomes a recoverable business outcome.</h1><p className="mt-4 max-w-2xl text-[12px] leading-6 text-white/42">The demo deliberately follows one storyline from group-level detection to branch diagnosis, clinician capacity, patient opportunity and action. That makes the product feel operational rather than like a collection of dashboards.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/tools/dental-control/branch/jeddah-tahlia" className="inline-flex items-center gap-2 rounded-xl bg-[#2aa89a] px-4 py-3 text-[11px] font-semibold text-[#04110f]">Start the live story <ArrowRight size={13}/></Link><Link href="/tools/dental-control/boardroom" className="inline-flex items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-[11px] font-medium text-white/65">Open boardroom intelligence</Link><Link href="/tools/dental-control/platform" className="inline-flex items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-[11px] font-medium text-white/65">Show platform depth</Link></div></div>
        <div className="rounded-3xl border border-[#2aa89a]/16 bg-gradient-to-br from-[#0d2822] to-[#0a1a16] p-5"><div className="text-[11px] font-semibold">Presenter opening</div><div className="mt-4 rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4 text-[12px] leading-6 text-white/56">“A dental group already has software. The problem is that leadership still cannot see, in one place, where capacity, revenue, claims and governance are breaking down. Sitora turns those disconnected systems into one operating intelligence layer.”</div><div className="mt-4 text-[9px] uppercase tracking-[0.15em] text-white/22">Then move directly into the Jeddah signal.</div></div>
      </section>

      <section className="mt-7 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex items-center gap-2 text-[13px] font-semibold"><Sparkles size={15} className="text-[#73cabf]"/> Five-step narrative</div><div className="mt-5 grid gap-3 xl:grid-cols-5">{demoJourney.map(step=><div key={step.step} className="relative rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#2aa89a]/12 text-[10px] font-semibold text-[#79cfc5]">{step.step}</div><div className="mt-4 text-[11px] font-semibold text-white/82">{step.title}</div><div className="mt-1 text-[9px] uppercase tracking-[0.11em] text-white/24">{step.screen}</div><p className="mt-3 text-[10px] leading-5 text-white/38">{step.narrative}</p><div className="mt-4 rounded-xl border border-[#c49a53]/12 bg-[#c49a53]/[0.035] p-2.5 text-[9px] text-[#e1c080]">Proof: {step.proof}</div>{step.step<5?<ArrowRight size={13} className="absolute -right-2 top-8 hidden text-white/14 xl:block"/>:null}</div>)}</div></section>

      <section className="mt-5 grid gap-4 lg:grid-cols-2">
        <Link href="/tools/dental-control/boardroom" className="group rounded-3xl border border-[#2aa89a]/15 bg-[#2aa89a]/[0.035] p-5 transition hover:border-[#2aa89a]/30"><div className="text-[10px] uppercase tracking-[0.16em] text-[#79cfc5]">Boardroom proof</div><div className="mt-2 text-[18px] font-semibold">What changed? Why? What should we do?</div><p className="mt-2 text-[10px] leading-5 text-white/36">Compare Riyadh North and Jeddah Tahlia, see day-over-day changes, and watch Sitora convert signals into an owned decision feed.</p><div className="mt-4 inline-flex items-center gap-2 text-[10px] text-[#7fd0c5]">Open Executive Boardroom <ArrowRight size={11} className="transition group-hover:translate-x-1"/></div></Link>
        <Link href="/tools/dental-control/platform" className="group rounded-3xl border border-violet-400/12 bg-violet-400/[0.025] p-5 transition hover:border-violet-400/25"><div className="text-[10px] uppercase tracking-[0.16em] text-violet-200/70">Platform proof</div><div className="mt-2 text-[18px] font-semibold">Show that the product can become much larger.</div><p className="mt-2 text-[10px] leading-5 text-white/36">Expose the connector layer, canonical data model, event fabric, intelligence services and future module catalogue.</p><div className="mt-4 inline-flex items-center gap-2 text-[10px] text-violet-200/70">Open Platform Centre <ArrowRight size={11} className="transition group-hover:translate-x-1"/></div></Link>
      </section>

      <section className="mt-5 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex items-center gap-2 text-[13px] font-semibold"><Layers3 size={15} className="text-[#73cabf]"/> Why this is a platform, not a feature</div><p className="mt-2 max-w-3xl text-[10px] leading-5 text-white/32">Every future feature plugs into the same canonical data and event fabric. That is the engineering story behind the prototype.</p><div className="mt-5 grid gap-3 lg:grid-cols-5">{platformLayers.map((layer,index)=><div key={layer.layer} className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="flex items-center gap-2"><div className="flex h-5 w-5 items-center justify-center rounded-full bg-white/[0.05] text-[8px] text-white/45">{index+1}</div><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#77cbbf]">{layer.layer}</div></div><div className="mt-3 space-y-1.5">{layer.items.map(item=><div key={item} className="flex items-center gap-2 text-[9px] text-white/38"><CheckCircle2 size={10} className="text-white/20"/>{item}</div>)}</div></div>)}</div></section>
    </main>
  </div>;
}
