"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Layers3, PlayCircle, Sparkles } from "lucide-react";
import { demoJourney, platformLayers } from "@/lib/dental-control/deep-data";

const liveRoute = [
  { href: "/tools/dental-control", cta: "Open Control Tower", time: "0:00–0:45" },
  { href: "/tools/dental-control/branch/jeddah-tahlia", cta: "Open Jeddah", time: "0:45–1:45" },
  { href: "/tools/dental-control/clinician/dr-faisal-al-zahrani", cta: "Open clinician", time: "1:45–2:35" },
  { href: "/tools/dental-control/patient/J-11307", cta: "Open patient story", time: "2:35–3:25" },
  { href: "/tools/dental-control/actions-live", cta: "Open Action Centre", time: "3:25–4:15" },
];

export function VCDemoJourney() {
  return <div className="min-h-screen bg-[#071310] text-white">
    <header className="border-b border-white/[0.06] bg-[#081713]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1320px] items-center justify-between px-4 py-4 md:px-7"><div className="flex items-center gap-3"><Link href="/tools/dental-control" className="rounded-xl border border-white/[0.08] p-2.5 text-white/50"><ArrowLeft size={17}/></Link><div><div className="text-[10px] uppercase tracking-[0.17em] text-[#73cabf]">Presenter mode</div><div className="mt-1 text-[17px] font-semibold">Sitora Dental Control · VC Demo</div></div></div><span className="hidden rounded-full border border-[#c49a53]/20 bg-[#c49a53]/8 px-3 py-1.5 text-[9px] uppercase tracking-[0.14em] text-[#e3c183] sm:inline-flex"><Sparkles size={11} className="mr-1.5"/> 5-minute story</span></div></header>

    <main className="mx-auto max-w-[1320px] px-4 py-7 md:px-7 md:py-9">
      <section className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#2aa89a]/18 bg-[#2aa89a]/[0.05] px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.16em] text-[#78cfc4]"><PlayCircle size={12}/> Guided executive story</div><h1 className="mt-4 max-w-3xl text-[32px] font-semibold tracking-[-0.04em] md:text-[44px]">From invisible operating leakage to an owned action in under five minutes.</h1><p className="mt-4 max-w-2xl text-[12px] leading-6 text-white/42">Start at the group view, identify Jeddah as the exception, prove the operational cause, trace one recoverable patient workflow and finish by assigning the action. No disconnected dashboard tour.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/tools/dental-control" className="inline-flex items-center gap-2 rounded-xl bg-[#2aa89a] px-4 py-3 text-[11px] font-semibold text-[#04110f]">Start at Control Tower <ArrowRight size={13}/></Link><Link href="/tools/dental-control/boardroom" className="inline-flex items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-[11px] font-medium text-white/65">Boardroom proof</Link><Link href="/tools/dental-control/platform" className="inline-flex items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-[11px] font-medium text-white/65">Platform proof</Link></div></div>

        <div className="rounded-3xl border border-[#2aa89a]/16 bg-gradient-to-br from-[#0d2822] to-[#0a1a16] p-5"><div className="flex items-center justify-between"><div className="text-[11px] font-semibold">30-second opening</div><span className="inline-flex items-center gap-1.5 text-[9px] text-white/28"><Clock3 size={11}/> do not over-explain</span></div><div className="mt-4 rounded-2xl border border-white/[0.06] bg-white/[0.03] p-4 text-[12px] leading-6 text-white/56">“Dental groups already have practice software. The problem is leadership still cannot see where chair capacity, accepted treatment, claims and record quality are leaking value across the group. Sitora sits above those systems, connects the signals, explains what matters and turns it into accountable action.”</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Proof label="Do not replace" value="Existing PMS"/><Proof label="Unify" value="Operating signals"/><Proof label="Outcome" value="Insight → action"/></div></div>
      </section>

      <section className="mt-7 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-[13px] font-semibold"><Sparkles size={15} className="text-[#73cabf]"/> Five-step live route</div><div className="mt-1 text-[10px] text-white/28">Each card opens the exact next screen. The final 45 seconds are reserved for the commercial/platform close.</div></div><span className="rounded-full border border-emerald-400/15 bg-emerald-400/[0.04] px-3 py-1.5 text-[9px] text-emerald-200">Target: 4m 15s product + 45s close</span></div><div className="mt-5 grid gap-3 xl:grid-cols-5">{demoJourney.map((step,index)=>{const route=liveRoute[index];return <Link href={route.href} key={step.step} className="group relative rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4 transition hover:border-[#2aa89a]/25 hover:bg-[#2aa89a]/[0.035]"><div className="flex items-center justify-between"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#2aa89a]/12 text-[10px] font-semibold text-[#79cfc5]">{step.step}</div><span className="text-[8px] uppercase tracking-[0.11em] text-white/22">{route.time}</span></div><div className="mt-4 text-[11px] font-semibold text-white/82">{step.title}</div><div className="mt-1 text-[9px] uppercase tracking-[0.11em] text-white/24">{step.screen}</div><p className="mt-3 text-[10px] leading-5 text-white/38">{step.narrative}</p><div className="mt-4 rounded-xl border border-[#c49a53]/12 bg-[#c49a53]/[0.035] p-2.5 text-[9px] text-[#e1c080]">Proof: {step.proof}</div><div className="mt-3 inline-flex items-center gap-1.5 text-[9px] font-medium text-[#79cfc5]">{route.cta}<ArrowRight size={10} className="transition group-hover:translate-x-1"/></div>{step.step<5?<ArrowRight size={13} className="absolute -right-2 top-8 hidden text-white/14 xl:block"/>:null}</Link>})}</div></section>

      <section className="mt-5 grid gap-4 lg:grid-cols-3">
        <div className="rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5"><div className="text-[10px] uppercase tracking-[0.16em] text-white/28">Closing line</div><div className="mt-2 text-[17px] font-semibold leading-7">“The product is not another dashboard. It is the operating layer that tells the group what changed, why, who owns it and whether the intervention worked.”</div></div>
        <Link href="/tools/dental-control/boardroom" className="group rounded-3xl border border-[#2aa89a]/15 bg-[#2aa89a]/[0.035] p-5 transition hover:border-[#2aa89a]/30"><div className="text-[10px] uppercase tracking-[0.16em] text-[#79cfc5]">Boardroom proof</div><div className="mt-2 text-[18px] font-semibold">What changed? Why? What should we do?</div><p className="mt-2 text-[10px] leading-5 text-white/36">Use this only if the investor wants more executive depth after the five-step product story.</p><div className="mt-4 inline-flex items-center gap-2 text-[10px] text-[#7fd0c5]">Open Executive Boardroom <ArrowRight size={11} className="transition group-hover:translate-x-1"/></div></Link>
        <Link href="/tools/dental-control/platform" className="group rounded-3xl border border-violet-400/12 bg-violet-400/[0.025] p-5 transition hover:border-violet-400/25"><div className="text-[10px] uppercase tracking-[0.16em] text-violet-200/70">Platform proof</div><div className="mt-2 text-[18px] font-semibold">Show why this can become a large product.</div><p className="mt-2 text-[10px] leading-5 text-white/36">Connectors, canonical data, event fabric, intelligence services and future modules all reuse the same core.</p><div className="mt-4 inline-flex items-center gap-2 text-[10px] text-violet-200/70">Open Platform Centre <ArrowRight size={11} className="transition group-hover:translate-x-1"/></div></Link>
      </section>

      <section className="mt-5 rounded-3xl border border-white/[0.07] bg-white/[0.025] p-5 md:p-6"><div className="flex items-center gap-2 text-[13px] font-semibold"><Layers3 size={15} className="text-[#73cabf]"/> Platform expansion story</div><p className="mt-2 max-w-3xl text-[10px] leading-5 text-white/32">Only open this section when asked how the prototype becomes a broader SaaS platform. Every future module plugs into the same canonical data and event fabric.</p><div className="mt-5 grid gap-3 lg:grid-cols-5">{platformLayers.map((layer,index)=><div key={layer.layer} className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="flex items-center gap-2"><div className="flex h-5 w-5 items-center justify-center rounded-full bg-white/[0.05] text-[8px] text-white/45">{index+1}</div><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#77cbbf]">{layer.layer}</div></div><div className="mt-3 space-y-1.5">{layer.items.map(item=><div key={item} className="flex items-center gap-2 text-[9px] text-white/38"><CheckCircle2 size={10} className="text-white/20"/>{item}</div>)}</div></div>)}</div></section>
    </main>
  </div>;
}

function Proof({label,value}:{label:string;value:string}) {
  return <div className="rounded-xl border border-white/[0.055] bg-white/[0.025] p-3"><div className="text-[8px] uppercase tracking-[0.11em] text-white/22">{label}</div><div className="mt-1 text-[10px] font-medium text-white/62">{value}</div></div>;
}
