'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, LogOut, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { jlrSupabase } from '@/lib/jlr-research-supabase';

type Row = {
  id:string; reference_number:string; submitted_at:string; contributor_type:string; contributor_name:string; organisation:string|null; email:string; phone:string|null;
  vehicle_model:string|null; vehicle_year:number|null; registration:string|null; vin_last6:string|null; engine_variant:string|null; engine_code:string|null; mileage:number|null; failure_date:string|null;
  failure_description:string; diagnosis:string|null; repair_outcome:string|null; repair_cost_gbp:number|null; replacement_engine:boolean|null; replacement_engine_type:string|null;
  prior_engine_failures:number; evidence_available:string[]; status:string; evidence_grade:string; verification_status:string; dedupe_status:string; counted_public:boolean; internal_notes:string|null;
};

export default function JlrAdminPage(){
 const [session,setSession]=useState<any>(null); const [rows,setRows]=useState<Row[]>([]); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [query,setQuery]=useState('');
 async function load(){setLoading(true); const {data,error}=await jlrSupabase.from('jlr_evidence_submissions').select('*').order('submitted_at',{ascending:false}).limit(500); if(error){setError('Access denied or unable to load the private evidence register.'); setRows([]);} else {setRows((data||[]) as Row[]); setError('');} setLoading(false);}
 useEffect(()=>{jlrSupabase.auth.getSession().then(({data})=>{setSession(data.session); if(data.session) load(); else setLoading(false)}); const {data}=jlrSupabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe();},[]);
 async function signIn(e:FormEvent){e.preventDefault();setError('');const {data,error}=await jlrSupabase.auth.signInWithPassword({email,password});if(error){setError('Sign-in failed.');return;}setSession(data.session);await load();}
 async function update(row:Row, patch:Partial<Row>){const {error}=await jlrSupabase.from('jlr_evidence_submissions').update(patch).eq('id',row.id); if(error){setError('Update failed.');return;} setRows(r=>r.map(x=>x.id===row.id?{...x,...patch}:x));}
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim(); if(!q)return rows; return rows.filter(r=>[r.reference_number,r.contributor_name,r.organisation,r.vehicle_model,r.registration,r.engine_variant,r.engine_code,r.diagnosis].filter(Boolean).join(' ').toLowerCase().includes(q));},[rows,query]);
 const stats=useMemo(()=>({total:rows.length,verified:rows.filter(r=>r.verification_status==='verified').length,duplicates:rows.filter(r=>r.dedupe_status==='duplicate').length,counted:rows.filter(r=>r.counted_public).length}),[rows]);
 if(!session)return <main className="min-h-screen bg-[#06192f] px-5 py-20 text-white"><div className="mx-auto max-w-md rounded-3xl border border-white/10 bg-white/[.05] p-8"><ShieldCheck className="h-9 w-9 text-[#f0a06f]"/><h1 className="mt-5 text-3xl font-black">Private research dashboard</h1><p className="mt-3 text-sm leading-6 text-slate-300">Authorised Sitora Research accounts only.</p><form onSubmit={signIn} className="mt-7 space-y-4"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" required className="w-full rounded-xl bg-white px-4 py-3 text-slate-900"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" required className="w-full rounded-xl bg-white px-4 py-3 text-slate-900"/><button className="w-full rounded-xl bg-[#c56f47] px-5 py-3 font-black">Sign in</button></form>{error&&<p className="mt-4 text-sm font-bold text-red-300">{error}</p>}</div></main>;
 return <main className="min-h-screen bg-[#eef3f7] text-[#0b1e36]"><header className="bg-[#06192f] text-white"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4 px-5 py-4"><a href="/research/jlr-tdv6-sdv6" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft className="h-4 w-4"/> Research home</a><div className="flex gap-2"><button onClick={load} className="rounded-lg border border-white/15 p-2"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>jlrSupabase.auth.signOut()} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-xs font-black"><LogOut className="h-4 w-4"/> Sign out</button></div></div></header>
 <section className="mx-auto max-w-[1600px] px-5 py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.18em] text-[#c56f47] uppercase">Stage 2 evidence register</p><h1 className="mt-2 text-4xl font-black">Research review dashboard</h1></div><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cases" className="w-72 rounded-xl border border-slate-300 bg-white py-3 pl-10 pr-4"/></label></div>
 <div className="mt-7 grid gap-4 sm:grid-cols-4">{[[stats.total,'Submissions'],[stats.verified,'Verified'],[stats.duplicates,'Duplicates'],[stats.counted,'Counted publicly']].map(([v,l])=><div key={String(l)} className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-3xl font-black">{v}</div><div className="mt-1 text-xs font-bold text-slate-500">{l}</div></div>)}</div>
 {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}
 <div className="mt-7 space-y-4">{loading?<p>Loading…</p>:filtered.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black text-[#c56f47]">{r.reference_number}</div><h2 className="mt-1 text-xl font-black">{r.vehicle_model||'Vehicle not supplied'} {r.vehicle_year||''}</h2><p className="mt-1 text-sm text-slate-500">{r.contributor_type} · {r.contributor_name}{r.organisation?` · ${r.organisation}`:''} · {new Date(r.submitted_at).toLocaleDateString('en-GB')}</p></div><div className="flex flex-wrap gap-2"><select value={r.status} onChange={e=>update(r,{status:e.target.value})} className="rounded-lg border px-3 py-2 text-xs font-bold"><option>new</option><option>triage</option><option>awaiting_evidence</option><option>verified</option><option>excluded</option><option>duplicate</option></select><select value={r.evidence_grade} onChange={e=>update(r,{evidence_grade:e.target.value})} className="rounded-lg border px-3 py-2 text-xs font-bold"><option value="unclassified">Grade —</option><option>A</option><option>B</option><option>C</option><option>D</option></select><select value={r.verification_status} onChange={e=>update(r,{verification_status:e.target.value})} className="rounded-lg border px-3 py-2 text-xs font-bold"><option>pending</option><option>partial</option><option>verified</option><option>disputed</option><option>excluded</option></select><select value={r.dedupe_status} onChange={e=>update(r,{dedupe_status:e.target.value})} className="rounded-lg border px-3 py-2 text-xs font-bold"><option>unchecked</option><option>unique</option><option>possible_duplicate</option><option>duplicate</option></select></div></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-4 text-sm"><div><b>Vehicle</b><p className="mt-1 text-slate-600">Reg: {r.registration||'—'} · VIN6: {r.vin_last6||'—'}<br/>Engine: {r.engine_variant||'—'} / {r.engine_code||'—'}<br/>Mileage: {r.mileage?.toLocaleString()||'—'}</p></div><div><b>Failure</b><p className="mt-1 text-slate-600">{r.failure_date||'Date unknown'}<br/>{r.failure_description}</p></div><div><b>Diagnosis / outcome</b><p className="mt-1 text-slate-600">{r.diagnosis||'—'}<br/>{r.repair_outcome||'—'} {r.repair_cost_gbp?`· £${r.repair_cost_gbp}`:''}</p></div><div><b>Evidence</b><p className="mt-1 text-slate-600">{r.evidence_available?.join(', ')||'None listed'}<br/>Prior failures: {r.prior_engine_failures}</p></div></div>
 <div className="mt-5 flex flex-wrap items-center gap-4 border-t pt-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={r.counted_public} onChange={e=>update(r,{counted_public:e.target.checked})}/> Include in verified public aggregate</label><span className="text-xs text-slate-400">Contact: {r.email}{r.phone?` · ${r.phone}`:''}</span></div></article>)}</div></section></main>;
}
