insert into trust360_rules (
  country,
  jurisdiction_code,
  category,
  subcategory,
  rule_code,
  rule_title,
  rule_summary,
  legal_reference,
  regulator,
  penalty_reference,
  trigger_fields,
  trigger_keywords,
  trigger_conditions,
  evidence_required,
  guidance,
  client_guidance,
  internal_guidance,
  severity,
  score_impact,
  package_relevance,
  applies_to_sectors,
  needs_legal_review
) values

-- =========================
-- QATAR — DATA PROTECTION
-- =========================

(
  'Qatar',
  'QA',
  'Data Protection & Privacy',
  'Privacy Notice',
  'QA-DP-001',
  'Personal data collection should be transparent and documented',
  'Where an organisation collects customer, employee, website-user or supplier personal data, it should be able to show what data is collected, why it is collected, how it is used, how long it is kept and who it is shared with.',
  'Law No. 13 of 2016 on Protecting Personal Data Privacy',
  'Ministry of Communications and Information Technology / relevant competent department',
  'Reported exposure can include significant financial penalties depending on the breach and applicable provision.',
  array['dataTypes', 'digitalChannels', 'existingDocuments'],
  array['personal data', 'customer data', 'employee data', 'website form', 'crm', 'privacy policy', 'lead forms'],
  '{"anySelected":["customer data","employee data","website forms","CRM","lead forms"]}'::jsonb,
  array[
    'privacy policy',
    'lead capture forms',
    'consent wording',
    'CRM data fields',
    'data retention process',
    'list of systems holding personal data',
    'vendor access list'
  ],
  'Review whether the organisation gives clear privacy information and maintains evidence of what personal data is collected, processed, shared and retained.',
  'Please provide your privacy policy, lead forms, consent wording, CRM fields and any document explaining how customer or employee data is handled.',
  'Check whether privacy notice covers purpose, processing basis, sharing, retention, rights, security and contact route.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Qatar',
  'QA',
  'Data Protection & Privacy',
  'Sensitive Data',
  'QA-DP-002',
  'Sensitive personal data requires stronger control',
  'If the organisation processes sensitive data such as health data, children’s data, ID/passport information, financial data, location data or images/videos, stronger evidence and safeguards are expected.',
  'Law No. 13 of 2016 on Protecting Personal Data Privacy',
  'Ministry of Communications and Information Technology / relevant competent department',
  'Higher-risk processing may increase regulatory and reputational exposure.',
  array['dataTypes', 'sector'],
  array['health data', 'children', 'qid', 'passport', 'financial data', 'location', 'photos', 'videos', 'biometric'],
  '{"anySelected":["health data","children data","QID/passport","financial data","photos/videos","location data"]}'::jsonb,
  array[
    'sensitive data register',
    'privacy notice',
    'consent wording',
    'access control list',
    'retention process',
    'breach response process',
    'vendor data-processing agreements'
  ],
  'Assess whether sensitive data is minimised, restricted, protected and supported by suitable notice, consent and access controls.',
  'Please provide details of any sensitive data you collect, including health, child, ID, financial, location, photo or video data.',
  'Flag as priority where sensitive data is processed without policy, access limits, consent trail or breach response.',
  'Urgent',
  18,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array['Healthcare / Clinic','Education / Nursery / School','Financial Services','QFC / Regulated Firm'],
  true
),

(
  'Qatar',
  'QA',
  'Data Protection & Privacy',
  'Data Subject Rights',
  'QA-DP-003',
  'Individuals should have a route to exercise privacy rights',
  'Organisations should have a documented process for handling privacy enquiries, correction/deletion requests and complaints relating to personal data.',
  'Law No. 13 of 2016 on Protecting Personal Data Privacy',
  'Ministry of Communications and Information Technology / relevant competent department',
  null,
  array['existingDocuments', 'concerns'],
  array['data subject request', 'privacy request', 'delete data', 'access request', 'complaint'],
  '{}'::jsonb,
  array[
    'privacy request process',
    'privacy contact email',
    'complaint handling process',
    'data correction/deletion workflow',
    'internal responsibility owner'
  ],
  'Check whether customers and users can raise privacy requests and whether staff know who owns the response.',
  'Please provide any process for handling privacy requests, deletion requests, correction requests or data complaints.',
  'If no documented owner exists, recommend simple privacy-request SOP.',
  'Medium',
  8,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Qatar',
  'QA',
  'Data Protection & Privacy',
  'Breach Readiness',
  'QA-DP-004',
  'Data breach response should be documented',
  'Organisations handling personal data should have a basic breach escalation and response process so incidents are recognised, contained, documented and escalated.',
  'Law No. 13 of 2016 on Protecting Personal Data Privacy',
  'Ministry of Communications and Information Technology / relevant competent department',
  null,
  array['cyberControls','existingDocuments','systemAccess'],
  array['breach', 'incident response', 'cyber incident', 'data leak', 'unauthorised access'],
  '{}'::jsonb,
  array[
    'incident response plan',
    'breach response process',
    'internal escalation chart',
    'vendor incident process',
    'cyber insurance or external support details if available'
  ],
  'Assess whether the organisation can respond quickly if customer data, website access, CRM data or marketing systems are compromised.',
  'Please provide any cyber incident, breach response or escalation process you currently use.',
  'Absence of breach process should reduce cyber and data protection score.',
  'High',
  12,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

-- =========================
-- QATAR — ADVERTISING / PRICING / CONSUMER
-- =========================

(
  'Qatar',
  'QA',
  'Advertising & Public Claims',
  'False or Deceptive Claims',
  'QA-ADV-001',
  'Public claims should be accurate, evidenced and not misleading',
  'Suppliers should avoid describing, advertising or displaying goods or services in a manner involving false or deceptive information.',
  'Law No. 8 of 2008 on Consumer Protection',
  'Ministry of Commerce and Industry / Consumer Protection and Combating Commercial Fraud Department',
  'Consumer protection enforcement can include inspections, corrective action, fines and commercial consequences.',
  array['marketingUses','digitalChannels'],
  array['advertising', 'claims', 'guarantee', 'best', 'number one', 'before and after', 'testimonial', 'results'],
  '{"anySelected":["paid ads","social media ads","testimonials","before/after claims","guarantees","performance claims"]}'::jsonb,
  array[
    'recent adverts',
    'landing pages',
    'social media posts',
    'claim evidence',
    'approval process',
    'testimonials/reviews used in marketing',
    'Arabic and English campaign versions'
  ],
  'Review marketing claims for accuracy, evidence, clarity and risk of misleading customers.',
  'Please provide recent adverts, landing pages, social posts, testimonials and evidence supporting key claims.',
  'Check for absolute claims, unsupported “best” claims, treatment/outcome claims and mismatched Arabic/English wording.',
  'High',
  14,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

(
  'Qatar',
  'QA',
  'Pricing & Promotions',
  'Price Display and Offer Transparency',
  'QA-PRICE-001',
  'Prices, discounts and promotional offers should be clear',
  'Where goods or services are displayed, price information and offer terms should be clear and not likely to mislead customers.',
  'Law No. 8 of 2008 on Consumer Protection',
  'Ministry of Commerce and Industry / Consumer Protection and Combating Commercial Fraud Department',
  null,
  array['marketingUses','digitalChannels'],
  array['discount', 'offer', 'promotion', 'price', 'sale', 'guarantee', 'refund'],
  '{"anySelected":["discounts/offers","pricing claims","promotions","limited-time offers"]}'::jsonb,
  array[
    'pricing pages',
    'offer terms',
    'discount rules',
    'promotion approval records',
    'refund/cancellation policy',
    'invoice examples if relevant'
  ],
  'Check whether prices, discounts, limitations, refund terms and promotions are clear before customers commit.',
  'Please provide recent offers, pricing pages, discount wording, refund/cancellation terms and any promotion approval process.',
  'Flag unclear “from” pricing, hidden charges, expired offers, unclear eligibility and weak refund wording.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array['Retail / E-commerce','Hospitality','Real Estate','Healthcare / Clinic','Professional Services'],
  true
),

(
  'Qatar',
  'QA',
  'Customer Experience & Complaint Risk',
  'Complaint Handling',
  'QA-CX-001',
  'Customer complaints should have an owner and process',
  'Consumer-facing organisations should have a clear route for handling complaints, refunds, cancellations, warranties and escalation.',
  'Law No. 8 of 2008 on Consumer Protection',
  'Ministry of Commerce and Industry / Consumer Protection and Combating Commercial Fraud Department',
  null,
  array['concerns','existingDocuments'],
  array['complaint', 'refund', 'cancellation', 'warranty', 'guarantee', 'customer service'],
  '{}'::jsonb,
  array[
    'complaint handling process',
    'refund/cancellation wording',
    'warranty wording',
    'customer service scripts',
    'recent anonymised complaints',
    'review response process'
  ],
  'Assess whether complaints are handled consistently and whether public promises match internal delivery.',
  'Please provide your complaint process, refund/cancellation wording, guarantee wording and any recent anonymised complaints.',
  'Complaint gaps increase reputational and consumer-protection risk.',
  'Medium',
  8,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

(
  'Qatar',
  'QA',
  'E-commerce / Online Sales',
  'Online Terms and Digital Acceptance',
  'QA-ECOM-001',
  'Online transactions should have clear terms and acceptance records',
  'Websites, apps and online sales journeys should clearly present terms, pricing, refund/cancellation details, contact details and acceptance records.',
  'Decree-Law No. 16 of 2010 on Electronic Transactions and Commerce',
  'Relevant Qatar authorities depending on activity',
  null,
  array['digitalChannels','existingDocuments'],
  array['e-commerce', 'checkout', 'online payment', 'booking', 'terms', 'refund', 'payment'],
  '{"anySelected":["online checkout","payment links","booking platform","customer portal","e-commerce"]}'::jsonb,
  array[
    'terms and conditions',
    'checkout screenshots',
    'payment/booking flow',
    'refund/cancellation policy',
    'customer confirmation emails',
    'digital acceptance records'
  ],
  'Review whether online customers see clear terms, pricing, cancellation/refund information and confirmation before purchase or booking.',
  'Please provide screenshots or links showing your online checkout, booking or payment journey.',
  'Check for missing terms, unclear acceptance, weak refund process and inconsistent customer confirmations.',
  'High',
  10,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array['Retail / E-commerce','Hospitality','Professional Services','Healthcare / Clinic'],
  true
),

-- =========================
-- QATAR — CYBER / VENDOR / AI
-- =========================

(
  'Qatar',
  'QA',
  'Cybersecurity & Access Control',
  'Admin Access and MFA',
  'QA-CYBER-001',
  'Admin access should be controlled and protected',
  'Organisations should maintain visibility over who has access to websites, CRM, email, cloud storage, payment systems and customer data, and should use MFA where possible.',
  'General cybersecurity and data protection good practice linked to privacy/security obligations',
  'Relevant technology/data protection authorities depending on activity',
  null,
  array['systemAccess','cyberControls'],
  array['admin access', 'developer', 'agency', 'crm', 'mfa', 'password', 'external access'],
  '{"anySelected":["external developer access","agency access","CRM access","cloud access","payment system access"]}'::jsonb,
  array[
    'admin user list',
    'MFA status',
    'password policy',
    'external access list',
    'offboarding process',
    'backup process'
  ],
  'Review whether access to critical systems is limited, protected and removed when no longer needed.',
  'Please provide a list of admin users and external parties who can access your website, CRM, email, cloud, booking or payment systems.',
  'High risk where external vendors retain admin access without MFA or offboarding.',
  'High',
  12,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  false
),

(
  'Qatar',
  'QA',
  'Vendor & Third-Party Risk',
  'Third-Party Data Access',
  'QA-VENDOR-001',
  'Vendors accessing data or systems should be recorded',
  'Where agencies, developers, IT providers, CRM providers, cloud platforms, payment providers or AI tools access systems or personal data, the organisation should maintain a vendor/access register.',
  'Law No. 13 of 2016 on Protecting Personal Data Privacy; general vendor risk controls',
  'Relevant Qatar authorities depending on activity',
  null,
  array['systemAccess','dataTypes'],
  array['vendor', 'agency', 'developer', 'crm', 'processor', 'third party', 'outsourcing'],
  '{"anySelected":["marketing agency","web developer","IT provider","CRM provider","payment provider","cloud provider","AI vendor"]}'::jsonb,
  array[
    'vendor list',
    'description of vendor access',
    'contracts/data-processing clauses',
    'overseas vendor details',
    'access review process',
    'offboarding process'
  ],
  'Assess whether third-party access is known, justified, documented and controlled.',
  'Please provide a vendor list showing who accesses your systems, website, CRM, customer data, marketing platforms or cloud tools.',
  'Flag overseas vendors and vendors touching sensitive data.',
  'High',
  14,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Qatar',
  'QA',
  'AI & Automation Use',
  'AI Tool Governance',
  'QA-AI-001',
  'AI usage should be governed where it touches customers, data or public content',
  'Where staff use AI tools for customer data, marketing content, support, HR, sales or public communications, the organisation should define what is allowed and how outputs are approved.',
  'Emerging AI governance, data protection and advertising-risk good practice',
  'Relevant Qatar authorities depending on sector/activity',
  null,
  array['aiUses','marketingUses','dataTypes'],
  array['AI', 'ChatGPT', 'chatbot', 'automation', 'AI content', 'customer data in AI'],
  '{"anySelected":["ChatGPT","AI chatbot","AI customer support","AI-generated marketing","AI HR/recruitment","AI customer data analysis"]}'::jsonb,
  array[
    'list of AI tools',
    'AI usage policy',
    'examples of AI-generated content',
    'human approval process',
    'rules on customer data entered into AI tools',
    'AI vendor list'
  ],
  'Review whether AI tools create privacy, advertising, customer-service or reputational risk.',
  'Please provide details of AI tools used by staff or systems, especially where AI touches customer data, marketing, HR, support or public content.',
  'High risk where customer/sensitive data is entered into public AI tools or AI-generated claims are published without review.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  false
),

-- =========================
-- SAUDI ARABIA — DATA PROTECTION
-- =========================

(
  'Saudi Arabia',
  'SA',
  'Data Protection & Privacy',
  'PDPL Privacy Notice',
  'SA-DP-001',
  'Personal data processing should be disclosed under Saudi PDPL expectations',
  'Organisations processing personal data of individuals in Saudi Arabia should provide clear information about collection, purpose, retention, rights, sharing and complaint routes.',
  'Saudi Personal Data Protection Law and Implementing Regulations',
  'Saudi Data & AI Authority (SDAIA)',
  'PDPL is enforceable; reported penalties can include substantial fines depending on violation.',
  array['dataTypes','digitalChannels','existingDocuments'],
  array['personal data', 'privacy policy', 'customer data', 'employee data', 'PDPL', 'Saudi data'],
  '{"anySelected":["customer data","employee data","website forms","CRM","lead forms"]}'::jsonb,
  array[
    'privacy policy',
    'data collection notices',
    'retention period statement',
    'data subject rights process',
    'complaint route',
    'CRM data fields',
    'data-sharing list'
  ],
  'Review whether the privacy notice and internal evidence align with Saudi PDPL expectations.',
  'Please provide privacy notices, data collection forms, CRM fields, retention wording and complaint/request routes.',
  'Saudi PDPL review should check retention period, data subject rights, destruction/copy request process and complaint route.',
  'High',
  14,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Data Protection & Privacy',
  'PDPL Consent and Legal Basis',
  'SA-DP-002',
  'Consent and processing basis should be evidenced',
  'Where personal data is processed for marketing, sensitive purposes or data sharing, the organisation should keep evidence of consent or other applicable processing basis.',
  'Saudi Personal Data Protection Law and Implementing Regulations',
  'Saudi Data & AI Authority (SDAIA)',
  null,
  array['marketingUses','dataTypes'],
  array['consent', 'marketing consent', 'sensitive data', 'WhatsApp', 'email marketing', 'SMS'],
  '{"anySelected":["WhatsApp marketing","email marketing","SMS marketing","health data","children data","financial data"]}'::jsonb,
  array[
    'consent wording',
    'consent records',
    'lead source records',
    'marketing list source',
    'unsubscribe/opt-out process',
    'sensitive data controls'
  ],
  'Assess whether consent and processing evidence exists for marketing, sensitive data and data sharing.',
  'Please provide consent wording, marketing list sources, opt-out process and evidence of consent where available.',
  'Marketing without consent trail should trigger marketing consent and privacy findings.',
  'High',
  14,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Data Protection & Privacy',
  'Cross-Border Transfers',
  'SA-DP-003',
  'Cross-border personal data transfers need safeguards',
  'Where personal data is transferred or accessed outside Saudi Arabia, the organisation should identify the transfer purpose, safeguards, vendors and records.',
  'Saudi PDPL Personal Data Transfer Regulation',
  'Saudi Data & AI Authority (SDAIA)',
  null,
  array['systemAccess','dataTypes'],
  array['overseas vendor', 'cross-border', 'cloud', 'international', 'processor', 'SCC'],
  '{"anySelected":["overseas vendors","international cloud provider","external processor","offshore support"]}'::jsonb,
  array[
    'overseas vendor list',
    'transfer purpose',
    'data categories transferred',
    'transfer safeguards',
    'contracts/SCCs if available',
    'risk assessment if available'
  ],
  'Review whether overseas access or transfer of personal data is mapped and supported by safeguards.',
  'Please provide details of overseas vendors, cloud providers or external processors that access Saudi personal data.',
  'Flag when Saudi customer/employee data is accessible by non-Saudi vendors without transfer records.',
  'High',
  16,
  array['Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Data Protection & Privacy',
  'Controller Registration / Governance',
  'SA-DP-004',
  'Data governance ownership should be documented',
  'Saudi PDPL compliance may require controller governance, accountability evidence and registration/records depending on applicability.',
  'Saudi Personal Data Protection Law and SDAIA guidance',
  'Saudi Data & AI Authority (SDAIA)',
  null,
  array['sector','companySize','qatarPresence'],
  array['SDAIA', 'controller', 'registration', 'governance', 'data officer'],
  '{}'::jsonb,
  array[
    'data protection owner',
    'processing register',
    'privacy governance responsibility',
    'controller registration evidence if applicable',
    'internal data policy'
  ],
  'Assess whether the organisation has clear ownership for Saudi data protection responsibilities.',
  'Please provide details of who owns data protection compliance and any processing register or controller registration evidence.',
  'Needs legal review for exact controller registration applicability.',
  'Medium',
  8,
  array['Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

-- =========================
-- SAUDI ARABIA — E-COMMERCE / ADS / CONSUMER
-- =========================

(
  'Saudi Arabia',
  'SA',
  'E-commerce / Online Sales',
  'Saudi E-Commerce Disclosure',
  'SA-ECOM-001',
  'E-commerce providers should give clear business, product and transaction information',
  'Saudi e-commerce rules require online providers to present clear information to consumers, including trader identity, product/service details, terms, pricing and transaction information.',
  'Saudi E-Commerce Law and Implementing Regulations',
  'Saudi Ministry of Commerce',
  null,
  array['digitalChannels','existingDocuments'],
  array['e-commerce', 'online store', 'checkout', 'payment', 'terms', 'Maroof', 'commercial registration'],
  '{"anySelected":["online checkout","e-commerce","payment links","booking platform","social commerce"]}'::jsonb,
  array[
    'commercial registration / e-commerce registration evidence',
    'website/app terms',
    'product/service descriptions',
    'pricing pages',
    'checkout screenshots',
    'refund/cancellation policy',
    'customer confirmation process'
  ],
  'Review whether the online sales journey gives consumers clear information before purchase.',
  'Please provide your online store/checkout links, terms, pricing pages, refund policy and registration details where applicable.',
  'Check identity disclosure, product description, terms, correction of mistakes, refunds and confirmation messages.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array['Retail / E-commerce','Hospitality','Professional Services'],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Advertising & Public Claims',
  'Advertising Claims and Influencer Content',
  'SA-ADV-001',
  'Advertising and influencer claims should be clear, accurate and evidenced',
  'Public advertising, influencer content, testimonials, discounts and product/service claims should be accurate, not misleading and supported by evidence.',
  'Saudi E-Commerce Law, consumer protection rules and platform/advertising requirements',
  'Saudi Ministry of Commerce and relevant media/advertising authorities',
  null,
  array['marketingUses','digitalChannels'],
  array['advertising', 'influencer', 'testimonial', 'discount', 'claim', 'guarantee', 'sponsored'],
  '{"anySelected":["paid ads","influencer content","testimonials","discounts/offers","performance claims"]}'::jsonb,
  array[
    'recent adverts',
    'influencer agreements/content',
    'claim evidence',
    'offer terms',
    'approval process',
    'Arabic campaign versions',
    'refund/guarantee wording'
  ],
  'Assess whether advertising content is clear, evidenced and not likely to mislead Saudi consumers.',
  'Please provide recent adverts, influencer posts, discount wording, testimonials and supporting evidence for claims.',
  'Flag sponsored content without disclosure, unsupported claims and unclear offer terms.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Customer Experience & Complaint Risk',
  'Complaint and Refund Handling',
  'SA-CX-001',
  'Consumers should have a clear complaint and resolution route',
  'Consumer-facing businesses should maintain clear routes for complaints, refunds, cancellations and after-sales support.',
  'Saudi Ministry of Commerce consumer guidance and applicable consumer/e-commerce rules',
  'Saudi Ministry of Commerce',
  null,
  array['existingDocuments','concerns'],
  array['complaint', 'refund', 'return', 'cancellation', 'warranty', 'customer service'],
  '{}'::jsonb,
  array[
    'complaint handling process',
    'refund/return process',
    'cancellation wording',
    'customer support templates',
    'recent anonymised complaints',
    'escalation process'
  ],
  'Review whether complaints and refunds are handled consistently and transparently.',
  'Please provide complaint, refund, cancellation and customer support processes.',
  'Weak complaints handling increases consumer escalation and reputation risk.',
  'Medium',
  8,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

-- =========================
-- SAUDI ARABIA — CYBER / AI / VENDOR
-- =========================

(
  'Saudi Arabia',
  'SA',
  'Cybersecurity & Access Control',
  'Access Control and Cyber Hygiene',
  'SA-CYBER-001',
  'Access to systems and personal data should be controlled',
  'Organisations should maintain access visibility, MFA, backup processes and incident response readiness for systems holding personal data or customer records.',
  'Saudi PDPL security obligations and general cybersecurity expectations',
  'SDAIA / relevant cybersecurity authorities depending on sector',
  null,
  array['systemAccess','cyberControls'],
  array['admin access', 'MFA', 'password', 'backup', 'incident response', 'CRM', 'cloud'],
  '{"anySelected":["CRM access","cloud access","external admin access","payment access","no MFA","no backup"]}'::jsonb,
  array[
    'admin user list',
    'MFA status',
    'password policy',
    'backup process',
    'incident response plan',
    'external access list'
  ],
  'Review whether critical systems and data are protected by basic access and incident controls.',
  'Please provide admin access lists, MFA status, backup process and incident response documents if available.',
  'Flag missing MFA, shared admin accounts and no offboarding.',
  'High',
  12,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'Vendor & Third-Party Risk',
  'Vendor and Processor Controls',
  'SA-VENDOR-001',
  'Vendors processing or accessing personal data should be mapped',
  'Where vendors, agencies, developers, CRM, cloud, AI or payment providers access Saudi personal data, the organisation should maintain records and contracts/safeguards.',
  'Saudi PDPL and Implementing Regulations',
  'Saudi Data & AI Authority (SDAIA)',
  null,
  array['systemAccess','dataTypes'],
  array['vendor', 'processor', 'agency', 'developer', 'cloud', 'AI vendor', 'payment provider'],
  '{"anySelected":["marketing agency","web developer","IT provider","CRM provider","cloud provider","AI vendor","payment provider"]}'::jsonb,
  array[
    'vendor register',
    'vendor access description',
    'contracts/data-processing clauses',
    'overseas vendor details',
    'access review process',
    'offboarding process'
  ],
  'Assess whether vendor access to data and systems is known, documented and controlled.',
  'Please provide a list of vendors and what data or systems they can access.',
  'Important for PDPL, transfer and breach accountability.',
  'High',
  14,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'Saudi Arabia',
  'SA',
  'AI & Automation Use',
  'AI Use and Personal Data',
  'SA-AI-001',
  'AI usage should not expose personal data or create misleading outputs',
  'AI tools used for marketing, support, HR, customer analysis or public content may create privacy, accuracy and reputational risks.',
  'Saudi PDPL and emerging AI/data governance expectations',
  'SDAIA / relevant sector authorities',
  null,
  array['aiUses','dataTypes','marketingUses'],
  array['AI', 'ChatGPT', 'chatbot', 'automation', 'AI content', 'customer data'],
  '{"anySelected":["ChatGPT","AI chatbot","AI-generated marketing","AI customer support","AI HR/recruitment","AI customer data analysis"]}'::jsonb,
  array[
    'AI tools list',
    'AI usage policy',
    'examples of AI-generated content',
    'approval process',
    'rules on customer data in AI',
    'AI vendor list'
  ],
  'Review whether AI usage creates privacy, accuracy, advertising or reputational exposure.',
  'Please provide details of AI tools used and examples of AI-generated public or customer-facing content.',
  'Flag customer/sensitive data entered into AI tools and AI claims published without review.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

-- =========================
-- UAE — DATA PROTECTION
-- =========================

(
  'UAE',
  'AE',
  'Data Protection & Privacy',
  'UAE PDPL Privacy Notice',
  'AE-DP-001',
  'Personal data processing should be transparent under UAE PDPL',
  'Organisations processing UAE personal data should be able to explain what data they collect, why, how it is used, who it is shared with, how long it is kept and how individuals can exercise rights.',
  'Federal Decree-Law No. 45 of 2021 on Personal Data Protection',
  'UAE Data Office / relevant UAE authorities',
  'Administrative penalties may apply depending on executive regulations and enforcement framework.',
  array['dataTypes','digitalChannels','existingDocuments'],
  array['personal data', 'privacy policy', 'UAE PDPL', 'customer data', 'employee data', 'website forms'],
  '{"anySelected":["customer data","employee data","website forms","CRM","lead forms"]}'::jsonb,
  array[
    'privacy policy',
    'lead forms',
    'consent wording',
    'data retention process',
    'data subject rights process',
    'data-sharing list',
    'vendor access list'
  ],
  'Review whether privacy notices and internal practices align with UAE PDPL expectations.',
  'Please provide privacy notices, data collection forms, consent wording, CRM fields and data retention details.',
  'Check transparency, rights, retention, processor sharing and security.',
  'High',
  14,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'UAE',
  'AE',
  'Data Protection & Privacy',
  'DPO / Higher-Risk Processing',
  'AE-DP-002',
  'Higher-risk processing may require stronger governance and DPO consideration',
  'Where processing is high-risk, large-scale, sensitive, systematic monitoring or otherwise significant, the organisation should assess whether stronger governance or a DPO is required.',
  'Federal Decree-Law No. 45 of 2021 on Personal Data Protection',
  'UAE Data Office / relevant UAE authorities',
  null,
  array['dataTypes','sector','companySize'],
  array['sensitive data', 'large scale', 'health data', 'children', 'financial data', 'monitoring', 'DPO'],
  '{"anySelected":["health data","children data","financial data","location data","large customer database"]}'::jsonb,
  array[
    'data protection owner',
    'DPO assessment if available',
    'sensitive data register',
    'DPIA/risk assessment if available',
    'access controls',
    'breach response plan'
  ],
  'Assess whether higher-risk UAE data processing has appropriate governance and ownership.',
  'Please provide any data protection owner details, DPO assessment, DPIA, sensitive data register or breach response plan.',
  'Needs legal review; mark as priority for regulated or sensitive sectors.',
  'High',
  12,
  array['Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array['Healthcare / Clinic','Education / Nursery / School','Financial Services','Government Supplier'],
  true
),

(
  'UAE',
  'AE',
  'Data Protection & Privacy',
  'Cross-Border Transfers',
  'AE-DP-003',
  'Cross-border transfers and overseas access should be mapped',
  'Where UAE personal data is stored, accessed or processed outside the UAE, the organisation should identify vendors, countries, safeguards and transfer purpose.',
  'Federal Decree-Law No. 45 of 2021 on Personal Data Protection',
  'UAE Data Office / relevant UAE authorities',
  null,
  array['systemAccess','dataTypes'],
  array['cross-border', 'overseas vendor', 'cloud', 'international', 'processor', 'offshore support'],
  '{"anySelected":["overseas vendors","international cloud provider","external processor","offshore support"]}'::jsonb,
  array[
    'overseas vendor list',
    'data categories transferred',
    'transfer purpose',
    'contracts/safeguards',
    'cloud hosting location if known',
    'vendor risk assessment if available'
  ],
  'Review whether overseas vendors or cloud providers create transfer risk or processor accountability issues.',
  'Please provide details of overseas vendors, cloud hosting and external processors that access UAE personal data.',
  'Flag when UAE customer data is accessible from outside UAE without transfer records.',
  'High',
  14,
  array['Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

-- =========================
-- UAE — CONSUMER / E-COMMERCE / ADS
-- =========================

(
  'UAE',
  'AE',
  'Advertising & Public Claims',
  'Misleading Advertising and Claims',
  'AE-ADV-001',
  'Advertising should be accurate and not misleading',
  'UAE consumer protection rules require suppliers and advertisers to avoid misleading promotion and provide clear information about goods and services.',
  'Federal Law No. 15 of 2020 on Consumer Protection and related executive regulations',
  'UAE Ministry of Economy / relevant local competent authorities',
  null,
  array['marketingUses','digitalChannels'],
  array['advertising', 'claim', 'discount', 'guarantee', 'testimonial', 'influencer', 'sponsored'],
  '{"anySelected":["paid ads","social media ads","testimonials","discounts/offers","performance claims","influencer content"]}'::jsonb,
  array[
    'recent adverts',
    'landing pages',
    'social media posts',
    'influencer content/agreements',
    'claim evidence',
    'offer terms',
    'approval process'
  ],
  'Review whether public claims are accurate, evidenced and not likely to mislead UAE consumers.',
  'Please provide recent adverts, landing pages, social posts, influencer content and evidence supporting key claims.',
  'Flag unsupported claims, undisclosed sponsored content and inconsistent offer terms.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

(
  'UAE',
  'AE',
  'Pricing & Promotions',
  'Clear Pricing and Harmful Terms',
  'AE-PRICE-001',
  'Pricing, discounts, refunds and online terms should be clear',
  'UAE consumer protection and e-commerce expectations require clear pricing, accurate product/service details, refund/cancellation information, warranties and avoidance of harmful or unfair terms.',
  'Federal Law No. 15 of 2020 on Consumer Protection; Federal Decree-Law No. 14 of 2023 on Trading through Modern Technology where applicable',
  'UAE Ministry of Economy / relevant local competent authorities',
  null,
  array['marketingUses','digitalChannels','existingDocuments'],
  array['price', 'discount', 'refund', 'cancellation', 'terms', 'warranty', 'hidden charges'],
  '{"anySelected":["discounts/offers","pricing claims","online checkout","e-commerce","payment links"]}'::jsonb,
  array[
    'pricing pages',
    'offer terms',
    'refund/cancellation policy',
    'terms and conditions',
    'warranty wording',
    'checkout screenshots',
    'customer confirmation messages'
  ],
  'Assess whether customers receive clear pricing and fair terms before committing online or offline.',
  'Please provide pricing pages, offer terms, refund/cancellation wording, terms, warranties and checkout screenshots.',
  'Check hidden charges, unilateral changes, unclear cancellation, weak refund terms and missing warranty information.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array['Retail / E-commerce','Hospitality','Real Estate','Professional Services'],
  true
),

(
  'UAE',
  'AE',
  'E-commerce / Online Sales',
  'Digital Trading Disclosure',
  'AE-ECOM-001',
  'Online traders should disclose key terms and transaction information',
  'Online businesses should provide clear identity, product/service information, pricing, delivery, cancellation/refund terms, warranties and customer support routes.',
  'Federal Decree-Law No. 14 of 2023 on Trading through Modern Technology; Federal Law No. 15 of 2020 on Consumer Protection',
  'UAE Ministry of Economy / relevant local competent authorities',
  null,
  array['digitalChannels','existingDocuments'],
  array['e-commerce', 'checkout', 'online payment', 'booking', 'app', 'digital platform'],
  '{"anySelected":["online checkout","e-commerce","app","booking platform","payment links","customer portal"]}'::jsonb,
  array[
    'website/app terms',
    'checkout screenshots',
    'payment flow',
    'refund/cancellation policy',
    'delivery/service fulfilment terms',
    'customer support route',
    'business identity details'
  ],
  'Review whether online trading pages give sufficient pre-contract information and customer support routes.',
  'Please provide your website/app checkout flow, terms, refund policy, delivery/service terms and customer support route.',
  'E-commerce gaps should affect website trust, customer experience and legal risk mapping.',
  'High',
  12,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array['Retail / E-commerce','Hospitality','Professional Services'],
  true
),

(
  'UAE',
  'AE',
  'Customer Experience & Complaint Risk',
  'Complaint and Dispute Handling',
  'AE-CX-001',
  'Customer complaints and disputes should be handled consistently',
  'Consumer-facing organisations should maintain clear complaint, refund, warranty and escalation processes.',
  'Federal Law No. 15 of 2020 on Consumer Protection',
  'UAE Ministry of Economy / relevant local competent authorities',
  null,
  array['existingDocuments','concerns'],
  array['complaint', 'refund', 'cancellation', 'warranty', 'customer service', 'dispute'],
  '{}'::jsonb,
  array[
    'complaint handling process',
    'refund/cancellation wording',
    'warranty process',
    'customer support templates',
    'recent anonymised complaints',
    'escalation route'
  ],
  'Assess whether customer complaints, refund requests and disputes can be handled consistently and evidenced.',
  'Please provide complaint, refund, warranty and escalation processes.',
  'Weak CX process creates consumer complaint and reputation exposure.',
  'Medium',
  8,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit'],
  array[],
  true
),

-- =========================
-- UAE — CYBER / VENDOR / AI / REPUTATION
-- =========================

(
  'UAE',
  'AE',
  'Cybersecurity & Access Control',
  'System Access and Cyber Readiness',
  'AE-CYBER-001',
  'Systems holding personal or customer data should have access controls',
  'Organisations should maintain visibility over admin access, MFA, backups and incident response for systems holding customer, employee or transaction data.',
  'UAE PDPL security expectations and UAE cybercrime/data misuse risk framework',
  'UAE Data Office / relevant cybersecurity and sector authorities',
  null,
  array['systemAccess','cyberControls'],
  array['admin access', 'MFA', 'password', 'backup', 'incident response', 'cloud', 'CRM'],
  '{"anySelected":["CRM access","cloud access","external admin access","payment access","no MFA","no backup"]}'::jsonb,
  array[
    'admin user list',
    'MFA status',
    'password policy',
    'backup process',
    'incident response plan',
    'external access list',
    'device/cloud access process'
  ],
  'Review whether critical systems and customer data are protected by basic access and incident controls.',
  'Please provide admin access lists, MFA status, backup process and incident response documents if available.',
  'Flag missing MFA, shared accounts, no backup and no incident process.',
  'High',
  12,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'UAE',
  'AE',
  'Vendor & Third-Party Risk',
  'Processor and Vendor Controls',
  'AE-VENDOR-001',
  'Vendors accessing UAE data or systems should be mapped',
  'Where vendors, agencies, developers, CRM, cloud, AI or payment providers access UAE personal data or systems, the organisation should maintain vendor/access records and contractual safeguards.',
  'Federal Decree-Law No. 45 of 2021 on Personal Data Protection',
  'UAE Data Office / relevant UAE authorities',
  null,
  array['systemAccess','dataTypes'],
  array['vendor', 'processor', 'agency', 'developer', 'cloud', 'payment provider', 'AI vendor'],
  '{"anySelected":["marketing agency","web developer","IT provider","CRM provider","cloud provider","payment provider","AI vendor"]}'::jsonb,
  array[
    'vendor register',
    'vendor access description',
    'contracts/data-processing clauses',
    'overseas vendor details',
    'access review process',
    'offboarding process'
  ],
  'Assess whether third-party system and data access is known, limited and evidenced.',
  'Please provide a vendor list showing who accesses your systems, customer data, website, CRM, payment tools or cloud platforms.',
  'Flag vendors with admin access, sensitive data or overseas access.',
  'High',
  14,
  array['SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'UAE',
  'AE',
  'AI & Automation Use',
  'AI Output and Data Governance',
  'AE-AI-001',
  'AI tools should not expose customer data or publish unreviewed claims',
  'AI use in marketing, customer support, HR, sales or analytics should be controlled so personal data is not exposed and public outputs are reviewed.',
  'UAE PDPL, consumer protection and emerging AI governance good practice',
  'UAE Data Office / relevant UAE authorities depending on sector',
  null,
  array['aiUses','dataTypes','marketingUses'],
  array['AI', 'ChatGPT', 'chatbot', 'automation', 'AI content', 'customer data'],
  '{"anySelected":["ChatGPT","AI chatbot","AI-generated marketing","AI customer support","AI HR/recruitment","AI customer data analysis"]}'::jsonb,
  array[
    'AI tools list',
    'AI usage policy',
    'examples of AI-generated content',
    'approval process',
    'rules on customer data in AI',
    'AI vendor list'
  ],
  'Review whether AI usage creates privacy, advertising, customer-service or reputational risk.',
  'Please provide details of AI tools used by staff or systems, especially where AI touches customer data or public content.',
  'Flag public AI-generated claims and sensitive data entered into external AI tools.',
  'High',
  12,
  array['Startup Trust Check','SME Trust 360 Audit','Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  true
),

(
  'UAE',
  'AE',
  'Reputation & Crisis Readiness',
  'Public Incident Readiness',
  'AE-REP-001',
  'Public complaints, data incidents and social media issues should have an escalation route',
  'Public-facing businesses should be prepared for customer complaints, viral posts, data incidents, review attacks or media enquiries.',
  'Reputation, consumer protection and digital-risk good practice',
  'Relevant UAE authorities depending on incident',
  null,
  array['concerns','existingDocuments','digitalChannels'],
  array['crisis', 'complaint', 'review', 'social media', 'incident', 'media'],
  '{}'::jsonb,
  array[
    'crisis response plan',
    'social media escalation process',
    'spokesperson/approval process',
    'review response process',
    'incident escalation chart',
    'public statement templates if available'
  ],
  'Assess whether the organisation can respond quickly and consistently to public-facing incidents.',
  'Please provide any crisis, review, media or social escalation process you currently use.',
  'Reputation readiness should influence executive report and 30/60/90 plan.',
  'Medium',
  8,
  array['Corporate Trust 360 Audit','Regulated Sector Trust Audit'],
  array[],
  false
)

on conflict (country, rule_code) do update set
  jurisdiction_code = excluded.jurisdiction_code,
  category = excluded.category,
  subcategory = excluded.subcategory,
  rule_title = excluded.rule_title,
  rule_summary = excluded.rule_summary,
  legal_reference = excluded.legal_reference,
  regulator = excluded.regulator,
  penalty_reference = excluded.penalty_reference,
  trigger_fields = excluded.trigger_fields,
  trigger_keywords = excluded.trigger_keywords,
  trigger_conditions = excluded.trigger_conditions,
  evidence_required = excluded.evidence_required,
  guidance = excluded.guidance,
  client_guidance = excluded.client_guidance,
  internal_guidance = excluded.internal_guidance,
  severity = excluded.severity,
  score_impact = excluded.score_impact,
  package_relevance = excluded.package_relevance,
  applies_to_sectors = excluded.applies_to_sectors,
  needs_legal_review = excluded.needs_legal_review,
  is_active = true,
  updated_at = now();